"""

Revision ID: 0229e8b16ccb
Revises: a968240d2ef9
Create Date: 2025-05-12 21:42:02.979160

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0229e8b16ccb'
down_revision = 'a968240d2ef9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('landing_metric', sa.Column('event', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('landing_metric', 'event')
    # ### end Alembic commands ###