"""

Revision ID: 02ac22dbbdfb
Revises: e678ff648bed
Create Date: 2025-03-02 14:35:22.565444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02ac22dbbdfb'
down_revision = 'e678ff648bed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###