"""

Revision ID: 02b5209bf490
Revises: cb278eda68a1
Create Date: 2025-07-20 16:18:16.002215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02b5209bf490'
down_revision = 'cb278eda68a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_feature_flag_name_project', 'feature_flag', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_feature_flag_name_project', 'feature_flag', ['name', 'project_id'])
    # ### end Alembic commands ###