"""

Revision ID: 0f22b27e42c4
Revises: 3f52e8b48c59
Create Date: 2025-08-01 11:49:37.996137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f22b27e42c4'
down_revision = '3f52e8b48c59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fragment_project_goal_usage',
    sa.Column('fragment_id', sa.Integer(), nullable=False),
    sa.Column('project_goal_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fragment_id'], ['fragment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_goal_id'], ['project_goal.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('fragment_id', 'project_goal_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fragment_project_goal_usage')
    # ### end Alembic commands ###