"""

Revision ID: 114e1b277c9f
Revises: 307453d1704e
Create Date: 2025-07-03 13:49:15.700995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '114e1b277c9f'
down_revision = '307453d1704e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('area', 'name')
    op.add_column('feature_flag', sa.Column('rotation_type', sa.Integer(), nullable=False))
    op.drop_column('variant', 'rotation_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('variant', sa.Column('rotation_type', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('feature_flag', 'rotation_type')
    op.add_column('area', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###