"""

Revision ID: 117f53523be3
Revises: 3ba00b3cf206
Create Date: 2025-08-20 14:20:47.161837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '117f53523be3'
down_revision = '3ba00b3cf206'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('client_project_id_fkey', 'client', type_='foreignkey')
    op.create_foreign_key(None, 'client', 'project', ['project_id'], ['id'], ondelete='CASCADE')
    op.alter_column('client_history', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('client_history', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'client', type_='foreignkey')
    op.create_foreign_key('client_project_id_fkey', 'client', 'project', ['project_id'], ['id'])
    # ### end Alembic commands ###