"""

Revision ID: 1459539bd7e7
Revises: 8a807cf5a409
Create Date: 2025-05-19 14:40:46.229699

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '1459539bd7e7'
down_revision = '8a807cf5a409'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # First remove any duplicate rows that would violate the constraint
    op.execute("""
        DELETE FROM project_goal a USING project_goal b
        WHERE a.id > b.id 
        AND a.project_id = b.project_id 
        AND a.target_action = b.target_action
    """)
    
    try:
        op.create_unique_constraint('unique_project_target_action', 'project_goal', ['project_id', 'target_action'])
    except sa.exc.OperationalError as e:
        # Constraint may already exist
        print(f"Warning: Could not create constraint: {e}")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_project_target_action', 'project_goal', type_='unique')
    # ### end Alembic commands ###
