"""

Revision ID: 1a2e0dacf904
Revises: f0ac7eda6382
Create Date: 2025-07-20 10:26:05.874828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a2e0dacf904'
down_revision = 'f0ac7eda6382'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('variant', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('variant', 'deleted_at')
    # ### end Alembic commands ###