"""

Revision ID: 1a75b63d8367
Revises: 84f5d05e2677
Create Date: 2025-07-03 10:42:50.716166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a75b63d8367'
down_revision = '84f5d05e2677'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###