"""

Revision ID: 1bbc6a438882
Revises: 02b5209bf490
Create Date: 2025-07-21 19:02:12.399227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bbc6a438882'
down_revision = '02b5209bf490'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_history', sa.Column('campaign_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'client_history', 'campaign', ['campaign_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'client_history', type_='foreignkey')
    op.drop_column('client_history', 'campaign_id')
    # ### end Alembic commands ###