"""

Revision ID: 1eff2cbf79b1
Revises: 43106f089329
Create Date: 2025-05-20 18:12:32.277840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1eff2cbf79b1'
down_revision = '43106f089329'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('campaign_area_id_fkey', 'campaign', type_='foreignkey')
    op.create_foreign_key(None, 'campaign', 'area', ['area_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'media', 'filesystem_directory', ['directory_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'media', type_='foreignkey')
    op.drop_constraint(None, 'campaign', type_='foreignkey')
    op.create_foreign_key('campaign_area_id_fkey', 'campaign', 'area', ['area_id'], ['id'])
    # ### end Alembic commands ###