"""

Revision ID: 21712c02ca62
Revises: b0b050fb443a
Create Date: 2025-04-18 16:21:23.367001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21712c02ca62'
down_revision = 'b0b050fb443a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###