"""

Revision ID: 26fe99f62de1
Revises: 21712c02ca62
Create Date: 2025-04-23 17:30:25.027293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26fe99f62de1'
down_revision = '21712c02ca62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stream_device_type_filter', 'toggled')
    op.drop_column('stream_geo_location_filter', 'toggled')
    op.drop_column('stream_os_type_filter', 'toggled')
    op.drop_column('stream_page_filter', 'toggled')
    op.drop_column('stream_time_frame_filter', 'toggled')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stream_time_frame_filter', sa.Column('toggled', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('stream_page_filter', sa.Column('toggled', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('stream_os_type_filter', sa.Column('toggled', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('stream_geo_location_filter', sa.Column('toggled', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('stream_device_type_filter', sa.Column('toggled', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###