"""

Revision ID: 307453d1704e
Revises: 561daa3d1235
Create Date: 2025-07-03 11:13:12.698926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '307453d1704e'
down_revision = '561daa3d1235'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('campaign', 'feature_flag_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('campaign', 'feature_flag_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###