"""

Revision ID: 3ba00b3cf206
Revises: df316b5508bf
Create Date: 2025-08-20 14:19:19.829692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ba00b3cf206'
down_revision = 'df316b5508bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###