"""

Revision ID: 3ef5a41af171
Revises: 8b39fb7d6e70
Create Date: 2025-03-02 14:53:14.676055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ef5a41af171'
down_revision = '8b39fb7d6e70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###