"""

Revision ID: 3f52e8b48c59
Revises: 5d344b8b1344
Create Date: 2025-08-01 11:46:58.303306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f52e8b48c59'
down_revision = '5d344b8b1344'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fragment_project_goal_usage')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fragment_project_goal_usage',
    sa.Column('fragment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('project_goal_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['fragment_id'], ['fragment.id'], name='fragment_project_goal_usage_fragment_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_goal_id'], ['project_goal.id'], name='fragment_project_goal_usage_project_goal_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('fragment_id', 'project_goal_id', name='fragment_project_goal_usage_pkey')
    )
    # ### end Alembic commands ###