"""

Revision ID: 41367ac01e2f
Revises: f112f664db30
Create Date: 2025-08-05 20:12:28.331218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41367ac01e2f'
down_revision = 'f112f664db30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('client_history_variant_id_fkey', 'client_history', type_='foreignkey')
    op.drop_constraint('client_history_area_id_fkey', 'client_history', type_='foreignkey')
    op.drop_constraint('client_history_goal_id_fkey', 'client_history', type_='foreignkey')
    op.drop_constraint('client_history_feature_flag_id_fkey', 'client_history', type_='foreignkey')
    op.drop_constraint('client_history_campaign_id_fkey', 'client_history', type_='foreignkey')
    op.create_foreign_key(None, 'client_history', 'feature_flag', ['feature_flag_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'client_history', 'campaign', ['campaign_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'client_history', 'area', ['area_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'client_history', 'project_goal', ['goal_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'client_history', 'variant', ['variant_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'client_history', type_='foreignkey')
    op.drop_constraint(None, 'client_history', type_='foreignkey')
    op.drop_constraint(None, 'client_history', type_='foreignkey')
    op.drop_constraint(None, 'client_history', type_='foreignkey')
    op.drop_constraint(None, 'client_history', type_='foreignkey')
    op.create_foreign_key('client_history_campaign_id_fkey', 'client_history', 'campaign', ['campaign_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('client_history_feature_flag_id_fkey', 'client_history', 'feature_flag', ['feature_flag_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('client_history_goal_id_fkey', 'client_history', 'project_goal', ['goal_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('client_history_area_id_fkey', 'client_history', 'area', ['area_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('client_history_variant_id_fkey', 'client_history', 'variant', ['variant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###