"""

Revision ID: 44035c91dd54
Revises: ef90710fc5ca
Create Date: 2025-05-21 20:02:48.309717

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '44035c91dd54'
down_revision = 'ef90710fc5ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('area', sa.Column('logo_id', sa.Integer(), nullable=True))
    op.alter_column('area', 'author_id', existing_type=sa.INTEGER(), nullable=True)
    op.create_index(op.f('ix_area_id'), 'area', ['id'], unique=False)
    op.create_foreign_key(None, 'area', 'media', ['logo_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('campaign_logo_id_fkey', 'campaign', type_='foreignkey')
    op.create_foreign_key(None, 'campaign', 'media', ['logo_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'campaign', 'area', ['area_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('project_logo_id_fkey', 'project', type_='foreignkey')
    op.create_foreign_key(None, 'project', 'media', ['logo_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_avatar_id_fkey', 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'media', ['avatar_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key('user_avatar_id_fkey', 'user', 'media', ['avatar_id'], ['id'])
    op.drop_constraint(None, 'project', type_='foreignkey')
    op.create_foreign_key('project_logo_id_fkey', 'project', 'media', ['logo_id'], ['id'])
    op.drop_constraint(None, 'campaign', type_='foreignkey')
    op.drop_constraint(None, 'campaign', type_='foreignkey')
    op.create_foreign_key('campaign_logo_id_fkey', 'campaign', 'media', ['logo_id'], ['id'])
    op.drop_constraint(None, 'area', type_='foreignkey')
    op.drop_index(op.f('ix_area_id'), table_name='area')
    op.alter_column('area', 'author_id', existing_type=sa.INTEGER(), nullable=False)
    op.drop_column('area', 'logo_id')
    # ### end Alembic commands ###
