"""

Revision ID: 4e24a205690c
Revises: 894609fab0b9
Create Date: 2025-07-30 22:04:33.517569

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4e24a205690c'
down_revision = '894609fab0b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fragment_project_goal_usage',
    sa.Column('fragment_id', sa.Integer(), nullable=False),
    sa.Column('project_goal_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fragment_id'], ['fragment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_goal_id'], ['project_goal.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('fragment_id', 'project_goal_id')
    )
    op.drop_index('ix_experiment_id', table_name='experiment')
    op.drop_constraint('campaign_experiment_id_fkey', 'campaign', type_='foreignkey')
    op.drop_column('campaign', 'experiment_id')
    op.drop_table('experiment')
    op.add_column('project_goal', sa.Column('success_level', sa.Float(), nullable=True))
    op.add_column('project_goal', sa.Column('failure_level', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_goal', 'failure_level')
    op.drop_column('project_goal', 'success_level')
    op.add_column('campaign', sa.Column('experiment_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('campaign_experiment_id_fkey', 'campaign', 'experiment', ['experiment_id'], ['id'])
    op.create_table('experiment',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('feature_flag_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['feature_flag_id'], ['feature_flag.id'], name='experiment_feature_flag_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='experiment_pkey'),
    sa.UniqueConstraint('name', name='experiment_name_key')
    )
    op.create_index('ix_experiment_id', 'experiment', ['id'], unique=False)
    op.drop_table('fragment_project_goal_usage')
    # ### end Alembic commands ###