"""

Revision ID: 4ec03505829c
Revises: 02ac22dbbdfb
Create Date: 2025-03-02 14:37:57.060578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ec03505829c'
down_revision = '02ac22dbbdfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'project', ['private_key_id'])
    op.drop_constraint('project_private_key_id_fkey', 'project', type_='foreignkey')
    op.create_foreign_key(None, 'project', 'project_api_key', ['private_key_id'], ['id'], ondelete='SET NULL')
    op.alter_column('project_api_key', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint(None, 'project_api_key', ['key'])
    op.create_foreign_key(None, 'project_api_key', 'project', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project_api_key', type_='foreignkey')
    op.drop_constraint(None, 'project_api_key', type_='unique')
    op.alter_column('project_api_key', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'project', type_='foreignkey')
    op.create_foreign_key('project_private_key_id_fkey', 'project', 'project_api_key', ['private_key_id'], ['id'])
    op.drop_constraint(None, 'project', type_='unique')
    # ### end Alembic commands ###