"""

Revision ID: 4f8d1f9ebefb
Revises: 93cd3100f170
Create Date: 2025-03-02 14:17:34.619736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f8d1f9ebefb'
down_revision = '93cd3100f170'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###