"""

Revision ID: 561daa3d1235
Revises: 1a75b63d8367
Create Date: 2025-07-03 10:49:58.176609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '561daa3d1235'
down_revision = '1a75b63d8367'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('variant_project_id_fkey', 'variant', type_='foreignkey')
    op.drop_column('variant', 'project_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('variant', sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('variant_project_id_fkey', 'variant', 'project', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###