"""

Revision ID: 574f0a613342
Revises: aac6e1c028d5
Create Date: 2025-07-14 10:37:33.167372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '574f0a613342'
down_revision = 'aac6e1c028d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###