"""

Revision ID: 5a77d44500ef
Revises: 4ad57a6b6f79
Create Date: 2025-07-20 07:29:11.646292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a77d44500ef'
down_revision = '4ad57a6b6f79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('campaign_feature_flag_id_fkey', 'campaign', type_='foreignkey')
    op.create_foreign_key(None, 'campaign', 'feature_flag', ['feature_flag_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('feature_flag_name_key', 'feature_flag', type_='unique')
    op.create_unique_constraint('uix_feature_flag_name_project', 'feature_flag', ['name', 'project_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_feature_flag_name_project', 'feature_flag', type_='unique')
    op.create_unique_constraint('feature_flag_name_key', 'feature_flag', ['name'])
    op.drop_constraint(None, 'campaign', type_='foreignkey')
    op.create_foreign_key('campaign_feature_flag_id_fkey', 'campaign', 'feature_flag', ['feature_flag_id'], ['id'])
    # ### end Alembic commands ###