"""

Revision ID: 5d344b8b1344
Revises: 65f0da84a44c
Create Date: 2025-07-31 15:50:36.152042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d344b8b1344'
down_revision = '65f0da84a44c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_history', sa.Column('goal_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'client_history', 'project_goal', ['goal_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'client_history', type_='foreignkey')
    op.drop_column('client_history', 'goal_id')
    # ### end Alembic commands ###