"""

Revision ID: 5d396f8596a0
Revises: 41367ac01e2f
Create Date: 2025-08-05 20:21:31.888888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d396f8596a0'
down_revision = '41367ac01e2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###