"""

Revision ID: 5db01980ac90
Revises: 4f8d1f9ebefb
Create Date: 2025-03-02 14:34:07.792428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5db01980ac90'
down_revision = '4f8d1f9ebefb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'project', ['private_key_id'])
    op.drop_constraint('project_private_key_id_fkey', 'project', type_='foreignkey')
    op.create_foreign_key(None, 'project', 'project_api_key', ['private_key_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project', type_='foreignkey')
    op.create_foreign_key('project_private_key_id_fkey', 'project', 'project_api_key', ['private_key_id'], ['id'])
    op.drop_constraint(None, 'project', type_='unique')
    # ### end Alembic commands ###