"""

Revision ID: 603d46bff048
Revises: 574f0a613342
Create Date: 2025-07-14 10:38:16.524656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '603d46bff048'
down_revision = '574f0a613342'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###