"""

Revision ID: 65f0da84a44c
Revises: 4e24a205690c
Create Date: 2025-07-31 12:10:15.310267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65f0da84a44c'
down_revision = '4e24a205690c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###