"""

Revision ID: 6ca94b4bd26d
Revises: d2a3314a007d
Create Date: 2025-07-14 10:40:58.957462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ca94b4bd26d'
down_revision = 'd2a3314a007d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_type_filter', sa.Column('condition_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'device_type_filter', 'condition', ['condition_id'], ['id'], ondelete='CASCADE')
    op.add_column('geo_location_filter', sa.Column('condition_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'geo_location_filter', 'condition', ['condition_id'], ['id'], ondelete='CASCADE')
    op.add_column('os_type_filter', sa.Column('condition_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'os_type_filter', 'condition', ['condition_id'], ['id'], ondelete='CASCADE')
    op.add_column('page_filter', sa.Column('condition_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'page_filter', 'condition', ['condition_id'], ['id'], ondelete='CASCADE')
    op.add_column('time_frame_filter', sa.Column('condition_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'time_frame_filter', 'condition', ['condition_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'time_frame_filter', type_='foreignkey')
    op.drop_column('time_frame_filter', 'condition_id')
    op.drop_constraint(None, 'page_filter', type_='foreignkey')
    op.drop_column('page_filter', 'condition_id')
    op.drop_constraint(None, 'os_type_filter', type_='foreignkey')
    op.drop_column('os_type_filter', 'condition_id')
    op.drop_constraint(None, 'geo_location_filter', type_='foreignkey')
    op.drop_column('geo_location_filter', 'condition_id')
    op.drop_constraint(None, 'device_type_filter', type_='foreignkey')
    op.drop_column('device_type_filter', 'condition_id')
    # ### end Alembic commands ###