"""

Revision ID: 73f16b626747
Revises: 5047dbd9bda3
Create Date: 2025-09-16 11:59:42.569848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73f16b626747'
down_revision = '5047dbd9bda3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_history', sa.Column('country_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_history', 'country_code')
    # ### end Alembic commands ###