"""

Revision ID: 75af808bacf9
Revises: 66b8aa2df6f7
Create Date: 2025-07-08 18:22:19.817304

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75af808bacf9'
down_revision = '66b8aa2df6f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_history', sa.Column('area_id', sa.Integer(), nullable=True))
    op.add_column('client_history', sa.Column('variant_id', sa.Integer(), nullable=True))
    op.add_column('client_history', sa.Column('event_type', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'client_history', 'area', ['area_id'], ['id'])
    op.create_foreign_key(None, 'client_history', 'variant', ['variant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'client_history', type_='foreignkey')
    op.drop_constraint(None, 'client_history', type_='foreignkey')
    op.drop_column('client_history', 'event_type')
    op.drop_column('client_history', 'variant_id')
    op.drop_column('client_history', 'area_id')
    # ### end Alembic commands ###