"""

Revision ID: 764f64442046
Revises: 99d2e236117b
Create Date: 2025-05-16 14:11:59.404819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '764f64442046'
down_revision = '99d2e236117b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_project_goal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('project_goal_id', sa.Integer(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['project_goal_id'], ['project_goal.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_project_goal_id'), 'client_project_goal', ['id'], unique=False)
    op.add_column('client', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'client', 'project', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'client', type_='foreignkey')
    op.drop_column('client', 'project_id')
    op.drop_index(op.f('ix_client_project_goal_id'), table_name='client_project_goal')
    op.drop_table('client_project_goal')
    # ### end Alembic commands ###