"""

Revision ID: 807697e97d18
Revises: c3a6f1dfae90
Create Date: 2025-07-14 11:00:13.339238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '807697e97d18'
down_revision = 'c3a6f1dfae90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###