"""

Revision ID: 8369df28bc5d
Revises: 1eff2cbf79b1
Create Date: 2025-05-20 18:15:22.563592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8369df28bc5d'
down_revision = '1eff2cbf79b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('campaign_area_id_fkey', 'campaign', type_='foreignkey')
    op.create_foreign_key(None, 'campaign', 'area', ['area_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'campaign', type_='foreignkey')
    op.create_foreign_key('campaign_area_id_fkey', 'campaign', 'area', ['area_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###