"""

Revision ID: 84f5d05e2677
Revises: fe5347ca2cd4
Create Date: 2025-07-02 20:02:26.381731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84f5d05e2677'
down_revision = 'fe5347ca2cd4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('variant', sa.Column('status', sa.Integer(), nullable=False))
    op.add_column('variant', sa.Column('rotation_type', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('variant', 'rotation_type')
    op.drop_column('variant', 'status')
    # ### end Alembic commands ###