"""

Revision ID: 894609fab0b9
Revises: c17b79414207
Create Date: 2025-07-30 15:20:03.994193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '894609fab0b9'
down_revision = 'c17b79414207'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_history', sa.Column('feature_flag_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'client_history', 'feature_flag', ['feature_flag_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'client_history', type_='foreignkey')
    op.drop_column('client_history', 'feature_flag_id')
    # ### end Alembic commands ###