"""

Revision ID: 8a807cf5a409
Revises: 764f64442046
Create Date: 2025-05-16 14:14:49.043064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a807cf5a409'
down_revision = '764f64442046'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###