"""

Revision ID: 8b189fd76764
Revises: 3ef5a41af171
Create Date: 2025-03-24 08:50:46.242635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b189fd76764'
down_revision = '3ef5a41af171'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_api_key', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_api_key', 'name')
    # ### end Alembic commands ###