"""

Revision ID: 8b39fb7d6e70
Revises: 4ec03505829c
Create Date: 2025-03-02 14:39:32.289210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b39fb7d6e70'
down_revision = '4ec03505829c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###