"""

Revision ID: 8c0f48f6894c
Revises: b2fcbd24c5e8
Create Date: 2025-08-01 11:54:16.903809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c0f48f6894c'
down_revision = 'b2fcbd24c5e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fragment_goals',
    sa.Column('fragment_id', sa.Integer(), nullable=False),
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fragment_id'], ['fragment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['goal_id'], ['project_goal.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('fragment_id', 'goal_id')
    )
    op.drop_table('fragment_project_goal_usage')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fragment_project_goal_usage',
    sa.Column('fragment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('project_goal_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['fragment_id'], ['fragment.id'], name='fragment_project_goal_usage_fragment_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_goal_id'], ['project_goal.id'], name='fragment_project_goal_usage_project_goal_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('fragment_id', 'project_goal_id', name='fragment_project_goal_usage_pkey')
    )
    op.drop_table('fragment_goals')
    # ### end Alembic commands ###