"""

Revision ID: 99d2e236117b
Revises: 84c65bcbe841
Create Date: 2025-05-13 21:12:22.116420

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '99d2e236117b'
down_revision = '84c65bcbe841'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('last_visited_at', sa.DateTime(), nullable=True))
    op.drop_column('client', 'last_visited')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('last_visited', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('client', 'last_visited_at')
    # ### end Alembic commands ###