"""

Revision ID: a950cbc381ba
Revises: 44035c91dd54
Create Date: 2025-06-29 19:45:09.314590

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a950cbc381ba'
down_revision = '44035c91dd54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_type_filter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_type', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_type_filter_id'), 'device_type_filter', ['id'], unique=False)
    op.create_table('geo_location_filter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geo_location_filter_id'), 'geo_location_filter', ['id'], unique=False)
    op.create_table('os_type_filter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('os_type', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_os_type_filter_id'), 'os_type_filter', ['id'], unique=False)
    op.create_table('page_filter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_page_filter_id'), 'page_filter', ['id'], unique=False)
    op.create_table('release_condition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_release_condition_id'), 'release_condition', ['id'], unique=False)
    op.create_table('time_frame_filter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_time', sa.DateTime(), nullable=False),
    sa.Column('to_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_time_frame_filter_id'), 'time_frame_filter', ['id'], unique=False)
    op.create_table('condition_set',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('release_condition_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['release_condition_id'], ['release_condition.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_condition_set_id'), 'condition_set', ['id'], unique=False)
    op.create_table('feature_flag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('release_condition_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['release_condition_id'], ['release_condition.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_feature_flag_id'), 'feature_flag', ['id'], unique=False)
    op.create_table('condition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('condition_set_id', sa.Integer(), nullable=False),
    sa.Column('filter_type', sa.Integer(), nullable=False),
    sa.Column('page_filter_id', sa.Integer(), nullable=True),
    sa.Column('device_type_filter_id', sa.Integer(), nullable=True),
    sa.Column('os_type_filter_id', sa.Integer(), nullable=True),
    sa.Column('time_frame_filter_id', sa.Integer(), nullable=True),
    sa.Column('geo_location_filter_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['condition_set_id'], ['condition_set.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['device_type_filter_id'], ['device_type_filter.id'], ),
    sa.ForeignKeyConstraint(['geo_location_filter_id'], ['geo_location_filter.id'], ),
    sa.ForeignKeyConstraint(['os_type_filter_id'], ['os_type_filter.id'], ),
    sa.ForeignKeyConstraint(['page_filter_id'], ['page_filter.id'], ),
    sa.ForeignKeyConstraint(['time_frame_filter_id'], ['time_frame_filter.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_condition_id'), 'condition', ['id'], unique=False)
    op.create_table('experiment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('feature_flag_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['feature_flag_id'], ['feature_flag.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_experiment_id'), 'experiment', ['id'], unique=False)
    op.create_table('variant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feature_flag_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('rollout_percentage', sa.Float(), nullable=False),
    sa.Column('fragment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['feature_flag_id'], ['feature_flag.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fragment_id'], ['fragment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_variant_id'), 'variant', ['id'], unique=False)
    op.drop_index('ix_campaign_os_type_filter_id', table_name='campaign_os_type_filter')
    op.drop_table('campaign_os_type_filter')
    op.drop_index('ix_campaign_page_filter_id', table_name='campaign_page_filter')
    op.drop_table('campaign_page_filter')
    op.drop_index('ix_campaign_time_frame_filter_id', table_name='campaign_time_frame_filter')
    op.drop_table('campaign_time_frame_filter')
    op.drop_index('ix_campaign_geo_location_filter_id', table_name='campaign_geo_location_filter')
    op.drop_table('campaign_geo_location_filter')
    op.drop_index('ix_campaign_device_type_filter_id', table_name='campaign_device_type_filter')
    op.drop_table('campaign_device_type_filter')
    op.add_column('campaign', sa.Column('release_condition_id', sa.Integer(), nullable=True))
    op.add_column('campaign', sa.Column('experiment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'campaign', 'experiment', ['experiment_id'], ['id'])
    op.create_foreign_key(None, 'campaign', 'release_condition', ['release_condition_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'campaign', type_='foreignkey')
    op.drop_constraint(None, 'campaign', type_='foreignkey')
    op.drop_column('campaign', 'experiment_id')
    op.drop_column('campaign', 'release_condition_id')
    op.create_table('campaign_device_type_filter',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('campaign_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('device_type', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], name='campaign_device_type_filter_campaign_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='campaign_device_type_filter_pkey')
    )
    op.create_index('ix_campaign_device_type_filter_id', 'campaign_device_type_filter', ['id'], unique=False)
    op.create_table('campaign_geo_location_filter',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('campaign_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('region', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], name='campaign_geo_location_filter_campaign_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='campaign_geo_location_filter_pkey')
    )
    op.create_index('ix_campaign_geo_location_filter_id', 'campaign_geo_location_filter', ['id'], unique=False)
    op.create_table('campaign_time_frame_filter',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('campaign_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('from_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('to_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], name='campaign_time_frame_filter_campaign_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='campaign_time_frame_filter_pkey')
    )
    op.create_index('ix_campaign_time_frame_filter_id', 'campaign_time_frame_filter', ['id'], unique=False)
    op.create_table('campaign_page_filter',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('campaign_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('page', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], name='campaign_page_filter_campaign_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='campaign_page_filter_pkey')
    )
    op.create_index('ix_campaign_page_filter_id', 'campaign_page_filter', ['id'], unique=False)
    op.create_table('campaign_os_type_filter',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('campaign_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('os_type', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], name='campaign_os_type_filter_campaign_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='campaign_os_type_filter_pkey')
    )
    op.create_index('ix_campaign_os_type_filter_id', 'campaign_os_type_filter', ['id'], unique=False)
    op.drop_index(op.f('ix_variant_id'), table_name='variant')
    op.drop_table('variant')
    op.drop_index(op.f('ix_experiment_id'), table_name='experiment')
    op.drop_table('experiment')
    op.drop_index(op.f('ix_condition_id'), table_name='condition')
    op.drop_table('condition')
    op.drop_index(op.f('ix_feature_flag_id'), table_name='feature_flag')
    op.drop_table('feature_flag')
    op.drop_index(op.f('ix_condition_set_id'), table_name='condition_set')
    op.drop_table('condition_set')
    op.drop_index(op.f('ix_time_frame_filter_id'), table_name='time_frame_filter')
    op.drop_table('time_frame_filter')
    op.drop_index(op.f('ix_release_condition_id'), table_name='release_condition')
    op.drop_table('release_condition')
    op.drop_index(op.f('ix_page_filter_id'), table_name='page_filter')
    op.drop_table('page_filter')
    op.drop_index(op.f('ix_os_type_filter_id'), table_name='os_type_filter')
    op.drop_table('os_type_filter')
    op.drop_index(op.f('ix_geo_location_filter_id'), table_name='geo_location_filter')
    op.drop_table('geo_location_filter')
    op.drop_index(op.f('ix_device_type_filter_id'), table_name='device_type_filter')
    op.drop_table('device_type_filter')
    # ### end Alembic commands ###