"""

Revision ID: a968240d2ef9
Revises: 26fe99f62de1
Create Date: 2025-05-12 21:05:38.819344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a968240d2ef9'
down_revision = '26fe99f62de1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('landing_metric',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('landing_id', sa.Integer(), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('referrer', sa.String(), nullable=True),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('subdomain', sa.String(), nullable=True),
    sa.Column('page_load_time', sa.Float(), nullable=True),
    sa.Column('device_type', sa.Integer(), nullable=True),
    sa.Column('os_type', sa.Integer(), nullable=True),
    sa.Column('browser', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('screen_width', sa.Integer(), nullable=True),
    sa.Column('screen_height', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['landing_id'], ['landing.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_landing_metric_id'), 'landing_metric', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_landing_metric_id'), table_name='landing_metric')
    op.drop_table('landing_metric')
    # ### end Alembic commands ###