"""

Revision ID: aac6e1c028d5
Revises: 75af808bacf9
Create Date: 2025-07-09 17:34:12.257041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aac6e1c028d5'
down_revision = '75af808bacf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('condition_geo_location_filter_id_fkey', 'condition', type_='foreignkey')
    op.drop_constraint('condition_device_type_filter_id_fkey', 'condition', type_='foreignkey')
    op.drop_constraint('condition_page_filter_id_fkey', 'condition', type_='foreignkey')
    op.drop_constraint('condition_os_type_filter_id_fkey', 'condition', type_='foreignkey')
    op.drop_constraint('condition_time_frame_filter_id_fkey', 'condition', type_='foreignkey')
    op.drop_column('condition', 'device_type_filter_id')
    op.drop_column('condition', 'page_filter_id')
    op.drop_column('condition', 'time_frame_filter_id')
    op.drop_column('condition', 'geo_location_filter_id')
    op.drop_column('condition', 'os_type_filter_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('condition', sa.Column('os_type_filter_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('condition', sa.Column('geo_location_filter_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('condition', sa.Column('time_frame_filter_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('condition', sa.Column('page_filter_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('condition', sa.Column('device_type_filter_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('condition_time_frame_filter_id_fkey', 'condition', 'time_frame_filter', ['time_frame_filter_id'], ['id'])
    op.create_foreign_key('condition_os_type_filter_id_fkey', 'condition', 'os_type_filter', ['os_type_filter_id'], ['id'])
    op.create_foreign_key('condition_page_filter_id_fkey', 'condition', 'page_filter', ['page_filter_id'], ['id'])
    op.create_foreign_key('condition_device_type_filter_id_fkey', 'condition', 'device_type_filter', ['device_type_filter_id'], ['id'])
    op.create_foreign_key('condition_geo_location_filter_id_fkey', 'condition', 'geo_location_filter', ['geo_location_filter_id'], ['id'])
    # ### end Alembic commands ###