"""

Revision ID: ab6206368d23
Revises: 2510b669b505
Create Date: 2025-08-05 20:32:43.217118

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ab6206368d23'
down_revision = '2510b669b505'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_client_project_goal_id', table_name='client_project_goal')
    op.drop_table('client_project_goal')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_project_goal',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('project_goal_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], name='client_project_goal_client_id_fkey'),
    sa.ForeignKeyConstraint(['project_goal_id'], ['project_goal.id'], name='client_project_goal_project_goal_id_fkey'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name='client_project_goal_project_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='client_project_goal_pkey')
    )
    op.create_index('ix_client_project_goal_id', 'client_project_goal', ['id'], unique=False)
    # ### end Alembic commands ###