"""

Revision ID: ae3c5b272750
Revises: 1459539bd7e7
Create Date: 2025-05-20 11:03:38.193395

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ae3c5b272750'
down_revision = '1459539bd7e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP TABLE IF EXISTS landing_metric CASCADE')
    op.execute('DROP TABLE IF EXISTS landing CASCADE')
    op.execute('DROP INDEX IF EXISTS ix_landing_id CASCADE')
    op.execute('DROP INDEX IF EXISTS ix_landing_metric_id CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('landing_metric',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('landing_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('campaign_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('referrer', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('domain', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('subdomain', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('page_load_time', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('device_type', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('os_type', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('browser', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('language', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('screen_width', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('screen_height', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('region', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('event', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], name='landing_metric_campaign_id_fkey'),
    sa.ForeignKeyConstraint(['landing_id'], ['landing.id'], name='landing_metric_landing_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='landing_metric_pkey')
    )
    op.create_index('ix_landing_metric_id', 'landing_metric', ['id'], unique=False)
    op.create_table('landing',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('stream_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fragment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('props', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('weight', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['fragment_id'], ['fragment.id'], name='landing_fragment_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name='landing_project_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stream_id'], ['stream.id'], name='landing_stream_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='landing_pkey')
    )
    op.create_index('ix_landing_id', 'landing', ['id'], unique=False)
    # ### end Alembic commands ###