"""

Revision ID: af5893411e48
Revises: a950cbc381ba
Create Date: 2025-06-29 19:50:29.143104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af5893411e48'
down_revision = 'a950cbc381ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign', sa.Column('feature_flag_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'campaign', 'feature_flag', ['feature_flag_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'campaign', type_='foreignkey')
    op.drop_column('campaign', 'feature_flag_id')
    # ### end Alembic commands ###