"""

Revision ID: b0b050fb443a
Revises: 8b189fd76764
Create Date: 2025-04-18 16:18:36.786265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0b050fb443a'
down_revision = '8b189fd76764'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('filename', sa.String(), nullable=False))
    op.add_column('media', sa.Column('content_type', sa.String(), nullable=False))
    op.add_column('media', sa.Column('data', sa.LargeBinary(), nullable=False))
    op.add_column('media', sa.Column('directory_id', sa.Integer(), nullable=True))
    op.alter_column('media', 'path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_foreign_key(None, 'media', 'filesystem_directory', ['directory_id'], ['id'])
    op.drop_column('media', 'public_path')
    op.drop_column('media', 'ext')
    op.drop_column('media', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('media', sa.Column('ext', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('media', sa.Column('public_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'media', type_='foreignkey')
    op.alter_column('media', 'path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('media', 'directory_id')
    op.drop_column('media', 'data')
    op.drop_column('media', 'content_type')
    op.drop_column('media', 'filename')
    # ### end Alembic commands ###