"""

Revision ID: b2fcbd24c5e8
Revises: 0f22b27e42c4
Create Date: 2025-08-01 11:51:15.037034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2fcbd24c5e8'
down_revision = '0f22b27e42c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###