"""

Revision ID: b63eec1d4022
Revises: 6ca94b4bd26d
Create Date: 2025-07-14 10:43:32.331406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b63eec1d4022'
down_revision = '6ca94b4bd26d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###