"""

Revision ID: bd90b923afb2
Revises: cf097148332e
Create Date: 2025-09-23 13:32:35.312154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd90b923afb2'
down_revision = 'cf097148332e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'fragment',
        sa.Column('favorite', sa.Boolean(), nullable=False, server_default=sa.false())
    )
    # (optional) if you want to remove the server_default after filling in:
    op.alter_column('fragment', 'favorite', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fragment', 'favorite')
    # ### end Alembic commands ###