"""

Revision ID: c17b79414207
Revises: 4589cee84d1c
Create Date: 2025-07-28 14:40:20.492061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c17b79414207'
down_revision = '4589cee84d1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('area', sa.Column('properties', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('area', 'properties')
    # ### end Alembic commands ###