"""

Revision ID: c3a6f1dfae90
Revises: b63eec1d4022
Create Date: 2025-07-14 10:57:23.274338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3a6f1dfae90'
down_revision = 'b63eec1d4022'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('release_condition', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'release_condition', 'project', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'release_condition', type_='foreignkey')
    op.drop_column('release_condition', 'project_id')
    # ### end Alembic commands ###