"""

Revision ID: cf097148332e
Revises: ac8763431065
Create Date: 2025-09-21 15:31:56.249621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf097148332e'
down_revision = 'ac8763431065'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('properties', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'properties')
    # ### end Alembic commands ###