"""

Revision ID: df316b5508bf
Revises: f13fe5ddb538
Create Date: 2025-08-20 14:18:25.111300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df316b5508bf'
down_revision = 'f13fe5ddb538'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###