"""

Revision ID: ef3d4f5dbbe2
Revises: dacfff700aac
Create Date: 2025-07-14 11:07:32.937206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef3d4f5dbbe2'
down_revision = 'dacfff700aac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('condition', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('condition', 'name')
    # ### end Alembic commands ###