"""

Revision ID: f0ac7eda6382
Revises: 5a77d44500ef
Create Date: 2025-07-20 10:23:49.676976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0ac7eda6382'
down_revision = '5a77d44500ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('area', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('campaign', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('feature_flag', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feature_flag', 'deleted_at')
    op.drop_column('campaign', 'deleted_at')
    op.drop_column('area', 'deleted_at')
    # ### end Alembic commands ###