"""

Revision ID: f112f664db30
Revises: d650cab1574a
Create Date: 2025-08-05 20:11:12.831897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f112f664db30'
down_revision = 'd650cab1574a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('client_history_area_id_fkey', 'client_history', type_='foreignkey')
    op.drop_constraint('client_history_client_id_fkey', 'client_history', type_='foreignkey')
    op.drop_constraint('client_history_variant_id_fkey', 'client_history', type_='foreignkey')
    op.drop_constraint('client_history_goal_id_fkey', 'client_history', type_='foreignkey')
    op.drop_constraint('client_history_feature_flag_id_fkey', 'client_history', type_='foreignkey')
    op.drop_constraint('client_history_campaign_id_fkey', 'client_history', type_='foreignkey')
    op.create_foreign_key(None, 'client_history', 'variant', ['variant_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'client_history', 'project_goal', ['goal_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'client_history', 'feature_flag', ['feature_flag_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'client_history', 'campaign', ['campaign_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'client_history', 'area', ['area_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'client_history', 'client', ['client_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'client_history', type_='foreignkey')
    op.drop_constraint(None, 'client_history', type_='foreignkey')
    op.drop_constraint(None, 'client_history', type_='foreignkey')
    op.drop_constraint(None, 'client_history', type_='foreignkey')
    op.drop_constraint(None, 'client_history', type_='foreignkey')
    op.drop_constraint(None, 'client_history', type_='foreignkey')
    op.create_foreign_key('client_history_campaign_id_fkey', 'client_history', 'campaign', ['campaign_id'], ['id'])
    op.create_foreign_key('client_history_feature_flag_id_fkey', 'client_history', 'feature_flag', ['feature_flag_id'], ['id'])
    op.create_foreign_key('client_history_goal_id_fkey', 'client_history', 'project_goal', ['goal_id'], ['id'])
    op.create_foreign_key('client_history_variant_id_fkey', 'client_history', 'variant', ['variant_id'], ['id'])
    op.create_foreign_key('client_history_client_id_fkey', 'client_history', 'client', ['client_id'], ['id'])
    op.create_foreign_key('client_history_area_id_fkey', 'client_history', 'area', ['area_id'], ['id'])
    # ### end Alembic commands ###