"""

Revision ID: f13fe5ddb538
Revises: ab6206368d23
Create Date: 2025-08-05 21:08:48.728085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f13fe5ddb538'
down_revision = 'ab6206368d23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client_history', sa.Column('page', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client_history', 'page')
    # ### end Alembic commands ###