"""

Revision ID: fe5347ca2cd4
Revises: af5893411e48
Create Date: 2025-07-02 17:18:35.199800

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe5347ca2cd4'
down_revision = 'af5893411e48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('campaign_fragment_id_fkey', 'campaign', type_='foreignkey')
    op.drop_constraint('campaign_release_condition_id_fkey', 'campaign', type_='foreignkey')
    op.drop_column('campaign', 'fragment_id')
    op.drop_column('campaign', 'release_condition_id')
    op.add_column('feature_flag', sa.Column('project_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'feature_flag', 'project', ['project_id'], ['id'], ondelete='CASCADE')
    op.add_column('variant', sa.Column('project_id', sa.Integer(), nullable=False))
    op.add_column('variant', sa.Column('props', sa.JSON(), nullable=True))
    op.create_foreign_key(None, 'variant', 'project', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'variant', type_='foreignkey')
    op.drop_column('variant', 'props')
    op.drop_column('variant', 'project_id')
    op.drop_constraint(None, 'feature_flag', type_='foreignkey')
    op.drop_column('feature_flag', 'project_id')
    op.add_column('campaign', sa.Column('release_condition_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('campaign', sa.Column('fragment_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('campaign_release_condition_id_fkey', 'campaign', 'release_condition', ['release_condition_id'], ['id'])
    op.create_foreign_key('campaign_fragment_id_fkey', 'campaign', 'fragment', ['fragment_id'], ['id'])
    # ### end Alembic commands ###