export const template = {
  _type: 'Document',
  _id: 'bb7b194a8a144',
  children: [
    {
      _type: 'Screen',
      _id: 'fffce172bf956',
      isPrimary: true,
      children: [
        {
          _type: 'Frame',
          _id: '342325463',
          parentKey: '$Screen:fffce172bf956',
          children: [
            {
              _type: 'Text',
              _id: 'ab737f0bacd6',
              width: 100,
              height: 100,
              rotation: 0,
              layoutSizingHorizontal: 'Relative',
              layoutSizingVertical: 'Fixed',
              visible: true,
              opacity: 1,
              content: [
                {
                  type: 'paragraph',
                  children: [
                    {
                      '0': 'T',
                      '1': 'e',
                      '2': 'x',
                      '3': 't',
                      '4': ':',
                      '5': 'a',
                      '6': 'b',
                      '7': '7',
                      '8': '3',
                      '9': '7',
                      '10': 'f',
                      '11': '0',
                      '12': 'b',
                      '13': 'a',
                      '14': 'c',
                      '15': 'd',
                      '16': '6',
                      '17': '.',
                      '18': 'c',
                      '19': 'o',
                      '20': 'n',
                      '21': 't',
                      '22': 'e',
                      '23': 'n',
                      '24': 't',
                      '25': '.',
                      '26': '0',
                      '27': '.',
                      '28': 'c',
                      '29': 'h',
                      '30': 'i',
                      '31': 'l',
                      '32': 'd',
                      '33': 'r',
                      '34': 'e',
                      '35': 'n',
                      '36': '.',
                      '37': '0'
                    }
                  ],
                  _type: 'Text',
                  _id: 'ab737f0bacd6.content.0'
                },
                {
                  type: 'paragraph',
                  children: [
                    {
                      '0': 'T',
                      '1': 'e',
                      '2': 'x',
                      '3': 't',
                      '4': ':',
                      '5': 'a',
                      '6': 'b',
                      '7': '7',
                      '8': '3',
                      '9': '7',
                      '10': 'f',
                      '11': '0',
                      '12': 'b',
                      '13': 'a',
                      '14': 'c',
                      '15': 'd',
                      '16': '6',
                      '17': '.',
                      '18': 'c',
                      '19': 'o',
                      '20': 'n',
                      '21': 't',
                      '22': 'e',
                      '23': 'n',
                      '24': 't',
                      '25': '.',
                      '26': '0',
                      '27': '.',
                      '28': 'c',
                      '29': 'h',
                      '30': 'i',
                      '31': 'l',
                      '32': 'd',
                      '33': 'r',
                      '34': 'e',
                      '35': 'n',
                      '36': '.',
                      '37': '0'
                    }
                  ],
                  _type: 'Text',
                  _id: 'ab737f0bacd6.content.0'
                },
                {
                  type: 'paragraph',
                  children: [
                    {
                      '0': 'T',
                      '1': 'e',
                      '2': 'x',
                      '3': 't',
                      '4': ':',
                      '5': 'a',
                      '6': 'b',
                      '7': '7',
                      '8': '3',
                      '9': '7',
                      '10': 'f',
                      '11': '0',
                      '12': 'b',
                      '13': 'a',
                      '14': 'c',
                      '15': 'd',
                      '16': '6',
                      '17': '.',
                      '18': 'c',
                      '19': 'o',
                      '20': 'n',
                      '21': 't',
                      '22': 'e',
                      '23': 'n',
                      '24': 't',
                      '25': '.',
                      '26': '0',
                      '27': '.',
                      '28': 'c',
                      '29': 'h',
                      '30': 'i',
                      '31': 'l',
                      '32': 'd',
                      '33': 'r',
                      '34': 'e',
                      '35': 'n',
                      '36': '.',
                      '37': '0'
                    }
                  ],
                  _type: 'Text',
                  _id: 'ab737f0bacd6.content.0'
                },
                {
                  type: 'paragraph',
                  children: [
                    {
                      '0': 'T',
                      '1': 'e',
                      '2': 'x',
                      '3': 't',
                      '4': ':',
                      '5': 'a',
                      '6': 'b',
                      '7': '7',
                      '8': '3',
                      '9': '7',
                      '10': 'f',
                      '11': '0',
                      '12': 'b',
                      '13': 'a',
                      '14': 'c',
                      '15': 'd',
                      '16': '6',
                      '17': '.',
                      '18': 'c',
                      '19': 'o',
                      '20': 'n',
                      '21': 't',
                      '22': 'e',
                      '23': 'n',
                      '24': 't',
                      '25': '.',
                      '26': '0',
                      '27': '.',
                      '28': 'c',
                      '29': 'h',
                      '30': 'i',
                      '31': 'l',
                      '32': 'd',
                      '33': 'r',
                      '34': 'e',
                      '35': 'n',
                      '36': '.',
                      '37': '0'
                    }
                  ],
                  _type: 'Text',
                  _id: 'ab737f0bacd6.content.0'
                },
                {
                  type: 'paragraph',
                  children: [
                    {
                      '0': 'T',
                      '1': 'e',
                      '2': 'x',
                      '3': 't',
                      '4': ':',
                      '5': 'a',
                      '6': 'b',
                      '7': '7',
                      '8': '3',
                      '9': '7',
                      '10': 'f',
                      '11': '0',
                      '12': 'b',
                      '13': 'a',
                      '14': 'c',
                      '15': 'd',
                      '16': '6',
                      '17': '.',
                      '18': 'c',
                      '19': 'o',
                      '20': 'n',
                      '21': 't',
                      '22': 'e',
                      '23': 'n',
                      '24': 't',
                      '25': '.',
                      '26': '0',
                      '27': '.',
                      '28': 'c',
                      '29': 'h',
                      '30': 'i',
                      '31': 'l',
                      '32': 'd',
                      '33': 'r',
                      '34': 'e',
                      '35': 'n',
                      '36': '.',
                      '37': '0'
                    }
                  ],
                  _type: 'Text',
                  _id: 'ab737f0bacd6.content.0'
                }
              ],
              parentKey: '$Frame:342325463'
            },
            {
              _type: 'Frame',
              _id: 'f7f5f84858bc9',
              children: [
                {
                  _type: 'Text',
                  _id: '878ac346e4921',
                  width: 100,
                  height: 100,
                  rotation: 0,
                  layoutSizingHorizontal: 'Hug',
                  layoutSizingVertical: 'Hug',
                  visible: true,
                  opacity: 1,
                  content: [
                    {
                      type: 'paragraph',
                      children: [
                        {
                          '0': 'T',
                          '1': 'e',
                          '2': 'x',
                          '3': 't',
                          '4': ':',
                          '5': '8',
                          '6': '7',
                          '7': '8',
                          '8': 'a',
                          '9': 'c',
                          '10': '3',
                          '11': '4',
                          '12': '6',
                          '13': 'e',
                          '14': '4',
                          '15': '9',
                          '16': '2',
                          '17': '1',
                          '18': '.',
                          '19': 'c',
                          '20': 'o',
                          '21': 'n',
                          '22': 't',
                          '23': 'e',
                          '24': 'n',
                          '25': 't',
                          '26': '.',
                          '27': '0',
                          '28': '.',
                          '29': 'c',
                          '30': 'h',
                          '31': 'i',
                          '32': 'l',
                          '33': 'd',
                          '34': 'r',
                          '35': 'e',
                          '36': 'n',
                          '37': '.',
                          '38': '0'
                        }
                      ],
                      _type: 'Text',
                      _id: '878ac346e4921.content.0'
                    },
                    {
                      type: 'paragraph',
                      children: [
                        {
                          '0': 'T',
                          '1': 'e',
                          '2': 'x',
                          '3': 't',
                          '4': ':',
                          '5': '8',
                          '6': '7',
                          '7': '8',
                          '8': 'a',
                          '9': 'c',
                          '10': '3',
                          '11': '4',
                          '12': '6',
                          '13': 'e',
                          '14': '4',
                          '15': '9',
                          '16': '2',
                          '17': '1',
                          '18': '.',
                          '19': 'c',
                          '20': 'o',
                          '21': 'n',
                          '22': 't',
                          '23': 'e',
                          '24': 'n',
                          '25': 't',
                          '26': '.',
                          '27': '0',
                          '28': '.',
                          '29': 'c',
                          '30': 'h',
                          '31': 'i',
                          '32': 'l',
                          '33': 'd',
                          '34': 'r',
                          '35': 'e',
                          '36': 'n',
                          '37': '.',
                          '38': '0'
                        }
                      ],
                      _type: 'Text',
                      _id: '878ac346e4921.content.0'
                    },
                    {
                      type: 'paragraph',
                      children: [
                        {
                          '0': 'T',
                          '1': 'e',
                          '2': 'x',
                          '3': 't',
                          '4': ':',
                          '5': '8',
                          '6': '7',
                          '7': '8',
                          '8': 'a',
                          '9': 'c',
                          '10': '3',
                          '11': '4',
                          '12': '6',
                          '13': 'e',
                          '14': '4',
                          '15': '9',
                          '16': '2',
                          '17': '1',
                          '18': '.',
                          '19': 'c',
                          '20': 'o',
                          '21': 'n',
                          '22': 't',
                          '23': 'e',
                          '24': 'n',
                          '25': 't',
                          '26': '.',
                          '27': '0',
                          '28': '.',
                          '29': 'c',
                          '30': 'h',
                          '31': 'i',
                          '32': 'l',
                          '33': 'd',
                          '34': 'r',
                          '35': 'e',
                          '36': 'n',
                          '37': '.',
                          '38': '0'
                        }
                      ],
                      _type: 'Text',
                      _id: '878ac346e4921.content.0'
                    },
                    {
                      type: 'paragraph',
                      children: [
                        {
                          '0': 'T',
                          '1': 'e',
                          '2': 'x',
                          '3': 't',
                          '4': ':',
                          '5': '8',
                          '6': '7',
                          '7': '8',
                          '8': 'a',
                          '9': 'c',
                          '10': '3',
                          '11': '4',
                          '12': '6',
                          '13': 'e',
                          '14': '4',
                          '15': '9',
                          '16': '2',
                          '17': '1',
                          '18': '.',
                          '19': 'c',
                          '20': 'o',
                          '21': 'n',
                          '22': 't',
                          '23': 'e',
                          '24': 'n',
                          '25': 't',
                          '26': '.',
                          '27': '0',
                          '28': '.',
                          '29': 'c',
                          '30': 'h',
                          '31': 'i',
                          '32': 'l',
                          '33': 'd',
                          '34': 'r',
                          '35': 'e',
                          '36': 'n',
                          '37': '.',
                          '38': '0'
                        }
                      ],
                      _type: 'Text',
                      _id: '878ac346e4921.content.0'
                    },
                    {
                      type: 'paragraph',
                      children: [
                        {
                          '0': 'T',
                          '1': 'e',
                          '2': 'x',
                          '3': 't',
                          '4': ':',
                          '5': '8',
                          '6': '7',
                          '7': '8',
                          '8': 'a',
                          '9': 'c',
                          '10': '3',
                          '11': '4',
                          '12': '6',
                          '13': 'e',
                          '14': '4',
                          '15': '9',
                          '16': '2',
                          '17': '1',
                          '18': '.',
                          '19': 'c',
                          '20': 'o',
                          '21': 'n',
                          '22': 't',
                          '23': 'e',
                          '24': 'n',
                          '25': 't',
                          '26': '.',
                          '27': '0',
                          '28': '.',
                          '29': 'c',
                          '30': 'h',
                          '31': 'i',
                          '32': 'l',
                          '33': 'd',
                          '34': 'r',
                          '35': 'e',
                          '36': 'n',
                          '37': '.',
                          '38': '0'
                        }
                      ],
                      _type: 'Text',
                      _id: '878ac346e4921.content.0'
                    },
                    {
                      type: 'paragraph',
                      children: [
                        {
                          '0': 'T',
                          '1': 'e',
                          '2': 'x',
                          '3': 't',
                          '4': ':',
                          '5': '8',
                          '6': '7',
                          '7': '8',
                          '8': 'a',
                          '9': 'c',
                          '10': '3',
                          '11': '4',
                          '12': '6',
                          '13': 'e',
                          '14': '4',
                          '15': '9',
                          '16': '2',
                          '17': '1',
                          '18': '.',
                          '19': 'c',
                          '20': 'o',
                          '21': 'n',
                          '22': 't',
                          '23': 'e',
                          '24': 'n',
                          '25': 't',
                          '26': '.',
                          '27': '0',
                          '28': '.',
                          '29': 'c',
                          '30': 'h',
                          '31': 'i',
                          '32': 'l',
                          '33': 'd',
                          '34': 'r',
                          '35': 'e',
                          '36': 'n',
                          '37': '.',
                          '38': '0'
                        }
                      ],
                      _type: 'Text',
                      _id: '878ac346e4921.content.0'
                    }
                  ],
                  parentKey: '$Frame:f7f5f84858bc9'
                }
              ],
              padding: 0,
              paddingLeft: 0,
              paddingRight: 0,
              paddingTop: 0,
              paddingBottom: 0,
              layerMode: 'none',
              layerAlign: 'start',
              layerDirection: 'horizontal',
              layerDistribute: 'start',
              layerWrap: false,
              layerGap: 0,
              width: 180,
              height: 40,
              rotation: 0,
              layoutSizingHorizontal: 'Fixed',
              layoutSizingVertical: 'Fixed',
              fills: {
                Solid: {
                  _type: 'Fill',
                  _id: '6d4a25f3c7c3f',
                  type: 'Solid',
                  color: {
                    r: 231,
                    g: 236,
                    b: 236,
                    a: 1,
                    _type: 'Fill',
                    _id: '6d4a25f3c7c3f.color'
                  }
                },
                _type: 'Frame',
                _id: 'f7f5f84858bc9.fills'
              },
              fillType: 'Solid',
              cornerRadius: 0,
              visible: true,
              opacity: 1,
              name: 'Button',
              parentKey: '$Frame:342325463'
            }
          ],
          padding: 10,
          paddingLeft: 0,
          paddingRight: 0,
          paddingTop: 0,
          paddingBottom: 0,
          layerMode: 'flex',
          layerAlign: 'center',
          layerDirection: 'horizontal',
          layerDistribute: 'start',
          layerWrap: false,
          layerGap: 0,
          width: 100,
          height: 100,
          rotation: 0,
          layoutSizingHorizontal: 'Relative',
          layoutSizingVertical: 'Hug',
          fills: {
            Solid: {
              _type: 'Fill',
              _id: 'ceefe4e28f4e3',
              type: 'Solid',
              color: {
                r: 59,
                g: 59,
                b: 59,
                a: 1,
                _type: 'Fill',
                _id: 'ceefe4e28f4e3.color'
              }
            },
            _type: 'Frame',
            _id: '342325463.fills'
          },
          fillType: 'Solid',
          cornerRadius: 0,
          visible: true,
          opacity: 1
        }
      ],
      padding: 0,
      paddingLeft: 0,
      paddingRight: 0,
      paddingTop: 0,
      paddingBottom: 0,
      layerMode: 'none',
      layerAlign: 'start',
      layerDirection: 'horizontal',
      layerDistribute: 'start',
      layerWrap: false,
      layerGap: 0,
      width: 320,
      height: 100,
      rotation: 0,
      layoutSizingHorizontal: 'Fixed',
      layoutSizingVertical: 'Hug',
      fills: {
        _type: 'Screen',
        _id: 'fffce172bf956.fills'
      },
      cornerRadius: 0,
      visible: true,
      opacity: 1
    }
  ]
}
