query CampaignDetail($id: Int!) {
    campaign(campaignId: $id) {
        id
        name
        active
        featureFlag {
            id
            releaseCondition {
                id
                conditionSets {
                    id
                    conditions {
                        id
                    }
                }
            }
        }
#        filters {
#            ... on FilterDeviceTypeGet {
#                deviceTypes
#            }
#            ... on FilterOSTypeGet {
#                osTypes
#            }
#            ... on FilterGeoLocationsGet {
#                geoLocations {
#                    city
#                    country
#                    region
#                }
#            }
#            ... on FilterPageGet {
#                pages
#            }
#            ... on FilterTimeFramesGet {
#                timeFrames {
#                    fromTime
#                    toTime
#                }
#            }
#        }
    }
}
