query CampaignDetail($campaignId: Int!) {
    campaign(campaignId: $campaignId) {
        id
        name
        active
        filters {
            ... on FilterDeviceTypeGet {
                deviceTypes
            }
            ... on FilterOSTypeGet {
                osTypes
            }
            ... on FilterGeoLocationsGet {
                geoLocations {
                    city
                    country
                    region
                }
            }
            ... on FilterPageGet {
                pages
            }
            ... on FilterTimeFramesGet {
                timeFrames {
                    fromTime
                    toTime
                }
            }
        }
    }
}
