mutation ChangeStreamActive($streamSlug: Int!, $campaignSlug: Int!, $active: Boolean!) {
    updateStream(strm: { id: $streamSlug, campaignId: $campaignSlug, active: $active }) {
        id
        active
    }
}
