# Dockerfile
FROM node:22

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

RUN npm install -y -g pnpm

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN pnpm install

# Copy the rest of the app
COPY . .

# Default command
CMD ["pnpm", "run", "dev"]
