version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: apps/web-next/Dockerfile.front
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules  # Prevent overwriting node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
