query AreasList($projectId: Int!) {
    area(projectId: $projectId) {
        id
        description
        defaultCampaign {
            id
            name
            logo {
                url: publicPath
            }
            status
        }
    }
}
