query AreasList($projectId: Int!) {
    areas(projectId: $projectId) {
        id
        name
        description
        defaultCampaign {
            logo {
                url: publicPath
            }
            active
        }
    }
}
