mutation CreateArea($name: String!, $description: String, $projectId: Int!) {
    createArea(area: { name: $name, description: $description, projectId: $projectId }
    ) {
        name
        description
        defaultCampaign {
            active
        }
    }
}

