mutation AuthSignUp ($email: String!, $password: String!, $firstName: String!, $lastName: String) {
    signup (userSignUp: {lastName: $lastName, firstName: $firstName, email: $email, password: $password}) {
        accessToken
        refreshToken
    }
}
