fragment ReleaseCondition on ReleaseConditionGet {
    id
    name
    conditionSets {
        id
        name
        conditions {
            id
            name
            filterData {
                ... on FilterDeviceTypeGet {
                    deviceTypes
                }
                ... on FilterOSTypeGet {
                    osTypes
                }
                ... on FilterTimeFramesGet {
                    timeFrames {
                        fromTime
                        toTime
                    }
                }
                ... on FilterPageGet {
                    pages
                }
                ... on FilterGeoLocationsGet {
                    geoLocations {
                        country
                        region
                        city
                    }
                }
            }
        }
    }
}
