mutation CreateProjectDirectory($projectSlug: Int!, $name: String!, $parentId: Int!) {
    createDirectory(directory: { projectId: $projectSlug, name: $name, parentId: $parentId }) {
        id
        name
        parentId
        projectId
    }
}
