query AreaConversionStatistics($areaId: Int!, $fromTs: DateTime!, $toTs: DateTime!, $prevFromTs: DateTime!, $prevToTs: DateTime!) {
    areaStatistic(statisticFilter:{dataIds: [$areaId], fromTs: $fromTs, toTs: $toTs, prevFromTs: $prevFromTs, prevToTs: $prevToTs}) {
        areaId
        areaCode
        trend {
            conversionTrend {
                difference
                trend
            }
        }
        currentStatistic {
            conversion
        }
    }
}
