version: "3.4"

networks:
  default:

services:
  nginx:
    build:
      context: nginx
    container_name: backend-fastapi-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - core
    networks:
      - default

  core: &service
    container_name: backend-fastapi-core
    environment:
      - RUN_LEVEL=dev
    entrypoint:
      - uvicorn
      - services.core:app
      - --host=0.0.0.0
      - --reload
    build:
      context: service
      dockerfile: deployment/docker/Dockerfile.server
      target: base
      args:
        RUN_LEVEL: dev
    volumes:
      - ./service:/opt/app
    networks:
      - default
    restart: unless-stopped
    env_file: .env
