"""

Revision ID: 03cee4657a38
Revises: 17744c4180a9
Create Date: 2025-01-07 12:15:27.200906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03cee4657a38'
down_revision = '17744c4180a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###