"""

Revision ID: 07fcae5c0d37
Revises: 88b39d7250c0
Create Date: 2025-01-04 16:38:39.461247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07fcae5c0d37'
down_revision = '88b39d7250c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fragment_media', sa.Column('fragment_version_id', sa.Integer(), nullable=True))
    op.drop_constraint('fragment_media_fragment_id_fkey', 'fragment_media', type_='foreignkey')
    op.create_foreign_key(None, 'fragment_media', 'fragment_version', ['fragment_version_id'], ['id'], ondelete='CASCADE')
    op.drop_column('fragment_media', 'fragment_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fragment_media', sa.Column('fragment_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'fragment_media', type_='foreignkey')
    op.create_foreign_key('fragment_media_fragment_id_fkey', 'fragment_media', 'fragment_version', ['fragment_id'], ['id'], ondelete='CASCADE')
    op.drop_column('fragment_media', 'fragment_version_id')
    # ### end Alembic commands ###