"""

Revision ID: 0d764b3ade86
Revises: 16240f79befe
Create Date: 2024-10-20 09:48:54.496788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d764b3ade86'
down_revision = '16240f79befe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'campaign', 'media', ['logo_id'], ['id'])
    op.create_foreign_key(None, 'project', 'media', ['logo_id'], ['id'])
    op.add_column('user', sa.Column('avatar_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'media', ['avatar_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'avatar_id')
    op.drop_constraint(None, 'project', type_='foreignkey')
    op.drop_constraint(None, 'campaign', type_='foreignkey')
    # ### end Alembic commands ###