"""

Revision ID: 1638a5afc5a0
Revises: 19a96c45a0f2
Create Date: 2024-10-13 16:23:48.540191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1638a5afc5a0'
down_revision = '19a96c45a0f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###