"""

Revision ID: 17744c4180a9
Revises: d7b32fd21107
Create Date: 2025-01-07 12:09:34.241681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17744c4180a9'
down_revision = 'd7b32fd21107'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('filesystem_project_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('item_type', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['filesystem_project_item.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_filesystem_project_item_id'), 'filesystem_project_item', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_filesystem_project_item_id'), table_name='filesystem_project_item')
    op.drop_table('filesystem_project_item')
    # ### end Alembic commands ###