"""

Revision ID: 1d9921caf11e
Revises: 3abf9df0b92c
Create Date: 2025-01-14 14:54:31.161365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d9921caf11e'
down_revision = '3abf9df0b92c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('linked_fragment', sa.Column('id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_linked_fragment_id'), 'linked_fragment', ['id'], unique=False)
    op.drop_constraint('linked_fragment_linked_fragment_id_fkey', 'linked_fragment', type_='foreignkey')
    op.drop_constraint('linked_fragment_fragment_id_fkey', 'linked_fragment', type_='foreignkey')
    op.create_foreign_key(None, 'linked_fragment', 'fragment', ['linked_fragment_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'linked_fragment', 'fragment', ['fragment_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'linked_fragment', type_='foreignkey')
    op.drop_constraint(None, 'linked_fragment', type_='foreignkey')
    op.create_foreign_key('linked_fragment_fragment_id_fkey', 'linked_fragment', 'fragment', ['fragment_id'], ['id'])
    op.create_foreign_key('linked_fragment_linked_fragment_id_fkey', 'linked_fragment', 'fragment', ['linked_fragment_id'], ['id'])
    op.drop_index(op.f('ix_linked_fragment_id'), table_name='linked_fragment')
    op.drop_column('linked_fragment', 'id')
    # ### end Alembic commands ###