"""

Revision ID: 20f8938dbf90
Revises: 41669308124f
Create Date: 2025-01-14 15:42:55.517758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20f8938dbf90'
down_revision = '41669308124f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###