"""

Revision ID: 228aa626ea93
Revises: 2c0a4dd0625c
Create Date: 2025-01-06 12:42:14.759224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '228aa626ea93'
down_revision = '2c0a4dd0625c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###