"""

Revision ID: 29ef78cbf746
Revises: 
Create Date: 2024-11-28 20:40:08.798615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29ef78cbf746'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feel', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(), nullable=True),
    sa.Column('page', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_id'), 'feedback', ['id'], unique=False)
    op.create_table('geo_location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geo_location_id'), 'geo_location', ['id'], unique=False)
    op.create_table('media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('ext', sa.String(), nullable=True),
    sa.Column('public_path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_id'), 'media', ['id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('avatar_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['avatar_id'], ['media.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('logo_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['logo_id'], ['media.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_id'), 'project', ['id'], unique=False)
    op.create_table('campaign',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('logo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['logo_id'], ['media.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaign_id'), 'campaign', ['id'], unique=False)
    op.create_table('fragment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('document', sa.JSON(), nullable=False),
    sa.Column('props', sa.JSON(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fragment_id'), 'fragment', ['id'], unique=False)
    op.create_table('project_members_role',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'project_id')
    )
    op.create_table('fragment_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=True),
    sa.Column('fragment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fragment_id'], ['fragment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fragment_media_id'), 'fragment_media', ['id'], unique=False)
    op.create_table('project_camnpaign',
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('campaign_id', 'project_id')
    )
    op.create_table('stream',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stream_id'), 'stream', ['id'], unique=False)
    op.create_table('campaign_stream',
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('stream_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['stream_id'], ['stream.id'], ),
    sa.PrimaryKeyConstraint('campaign_id', 'stream_id')
    )
    op.create_table('landing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('stream_id', sa.Integer(), nullable=False),
    sa.Column('fragment_id', sa.Integer(), nullable=True),
    sa.Column('props', sa.JSON(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['fragment_id'], ['fragment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stream_id'], ['stream.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_landing_id'), 'landing', ['id'], unique=False)
    op.create_table('stream_device_type_filter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stream_id', sa.Integer(), nullable=True),
    sa.Column('device_type', sa.Integer(), nullable=False),
    sa.Column('toggled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['stream_id'], ['stream.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stream_device_type_filter_id'), 'stream_device_type_filter', ['id'], unique=False)
    op.create_table('stream_geo_location_filter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stream_id', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('toggled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['stream_id'], ['stream.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stream_geo_location_filter_id'), 'stream_geo_location_filter', ['id'], unique=False)
    op.create_table('stream_os_type_filter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stream_id', sa.Integer(), nullable=True),
    sa.Column('os_type', sa.Integer(), nullable=False),
    sa.Column('toggled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['stream_id'], ['stream.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stream_os_type_filter_id'), 'stream_os_type_filter', ['id'], unique=False)
    op.create_table('stream_page_filter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stream_id', sa.Integer(), nullable=True),
    sa.Column('page', sa.String(), nullable=False),
    sa.Column('toggled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['stream_id'], ['stream.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stream_page_filter_id'), 'stream_page_filter', ['id'], unique=False)
    op.create_table('stream_time_frame_filter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stream_id', sa.Integer(), nullable=True),
    sa.Column('from_time', sa.DateTime(), nullable=False),
    sa.Column('to_time', sa.DateTime(), nullable=False),
    sa.Column('toggled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['stream_id'], ['stream.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stream_time_frame_filter_id'), 'stream_time_frame_filter', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stream_time_frame_filter_id'), table_name='stream_time_frame_filter')
    op.drop_table('stream_time_frame_filter')
    op.drop_index(op.f('ix_stream_page_filter_id'), table_name='stream_page_filter')
    op.drop_table('stream_page_filter')
    op.drop_index(op.f('ix_stream_os_type_filter_id'), table_name='stream_os_type_filter')
    op.drop_table('stream_os_type_filter')
    op.drop_index(op.f('ix_stream_geo_location_filter_id'), table_name='stream_geo_location_filter')
    op.drop_table('stream_geo_location_filter')
    op.drop_index(op.f('ix_stream_device_type_filter_id'), table_name='stream_device_type_filter')
    op.drop_table('stream_device_type_filter')
    op.drop_index(op.f('ix_landing_id'), table_name='landing')
    op.drop_table('landing')
    op.drop_table('campaign_stream')
    op.drop_index(op.f('ix_stream_id'), table_name='stream')
    op.drop_table('stream')
    op.drop_table('project_camnpaign')
    op.drop_index(op.f('ix_fragment_media_id'), table_name='fragment_media')
    op.drop_table('fragment_media')
    op.drop_table('project_members_role')
    op.drop_index(op.f('ix_fragment_id'), table_name='fragment')
    op.drop_table('fragment')
    op.drop_index(op.f('ix_campaign_id'), table_name='campaign')
    op.drop_table('campaign')
    op.drop_index(op.f('ix_project_id'), table_name='project')
    op.drop_table('project')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_media_id'), table_name='media')
    op.drop_table('media')
    op.drop_index(op.f('ix_geo_location_id'), table_name='geo_location')
    op.drop_table('geo_location')
    op.drop_index(op.f('ix_feedback_id'), table_name='feedback')
    op.drop_table('feedback')
    # ### end Alembic commands ###