"""

Revision ID: 2c0a4dd0625c
Revises: 9ed26d75b8cd
Create Date: 2025-01-06 12:41:35.486444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c0a4dd0625c'
down_revision = '9ed26d75b8cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###