"""

Revision ID: 33e09518dc7f
Revises: d725a52d97f2
Create Date: 2025-01-14 15:13:52.504803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33e09518dc7f'
down_revision = 'd725a52d97f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###