"""

Revision ID: 34f47db0b297
Revises: ff4942da4db5
Create Date: 2024-11-26 20:01:09.659657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34f47db0b297'
down_revision = 'ff4942da4db5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('geo_location', 'region',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('geo_location', 'region',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###