"""

Revision ID: 3b49dbb0f78c
Revises: 67fdec203acf
Create Date: 2025-01-14 16:05:00.198984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b49dbb0f78c'
down_revision = '67fdec203acf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###