"""

Revision ID: 3f5b881d3d0c
Revises: b7a71c280d67
Create Date: 2025-01-14 15:40:33.933890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f5b881d3d0c'
down_revision = 'b7a71c280d67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###