"""

Revision ID: 41669308124f
Revises: 3f5b881d3d0c
Create Date: 2025-01-14 15:41:56.272223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41669308124f'
down_revision = '3f5b881d3d0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###