"""

Revision ID: 58c15a4657aa
Revises: 33e09518dc7f
Create Date: 2025-01-14 15:19:15.507450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58c15a4657aa'
down_revision = '33e09518dc7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###