"""

Revision ID: 634d046db754
Revises: c5936808f98a
Create Date: 2024-11-06 10:50:59.672138

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '634d046db754'
down_revision = 'c5936808f98a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('landing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('stream_id', sa.Integer(), nullable=False),
    sa.Column('fragment_id', sa.Integer(), nullable=False),
    sa.Column('props', sa.JSON(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['fragment_id'], ['fragment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stream_id'], ['stream.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_landing_id'), 'landing', ['id'], unique=False)
    op.drop_index('ix_stream_fragment_id', table_name='stream_fragment')
    op.drop_table('stream_fragment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stream_fragment',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('stream_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fragment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('props', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('weight', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['fragment_id'], ['fragment.id'], name='stream_fragment_fragment_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name='stream_fragment_project_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stream_id'], ['stream.id'], name='stream_fragment_stream_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='stream_fragment_pkey')
    )
    op.create_index('ix_stream_fragment_id', 'stream_fragment', ['id'], unique=False)
    op.drop_index(op.f('ix_landing_id'), table_name='landing')
    op.drop_table('landing')
    # ### end Alembic commands ###