"""

Revision ID: 647961079d99
Revises: 80950d847c0f
Create Date: 2024-10-14 20:00:06.479944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '647961079d99'
down_revision = '80950d847c0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###