"""

Revision ID: 67fdec203acf
Revises: 8239f8c8d622
Create Date: 2025-01-14 16:03:29.308774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67fdec203acf'
down_revision = '8239f8c8d622'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###