"""

Revision ID: 6fedbb00b4b1
Revises: fb816be4ef5f
Create Date: 2025-01-29 18:35:34.745849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fedbb00b4b1'
down_revision = 'fb816be4ef5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###