"""

Revision ID: 7800657f96c6
Revises: 634d046db754
Create Date: 2024-11-06 11:02:36.457236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7800657f96c6'
down_revision = '634d046db754'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('landing', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('landing', sa.Column('deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('landing', 'deleted')
    op.drop_column('landing', 'active')
    # ### end Alembic commands ###