"""

Revision ID: 7bc6b9ac70c4
Revises: 0d764b3ade86
Create Date: 2024-10-22 19:43:19.187621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bc6b9ac70c4'
down_revision = '0d764b3ade86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fragment_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=True),
    sa.Column('fragment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fragment_id'], ['media.id'], ),
    sa.ForeignKeyConstraint(['media_id'], ['fragment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fragment_media_id'), 'fragment_media', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_fragment_media_id'), table_name='fragment_media')
    op.drop_table('fragment_media')
    # ### end Alembic commands ###