"""

Revision ID: 80950d847c0f
Revises: 81620c1490e9
Create Date: 2024-10-14 18:46:39.318629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80950d847c0f'
down_revision = '81620c1490e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###