"""

Revision ID: 81620c1490e9
Revises: 1638a5afc5a0
Create Date: 2024-10-14 18:33:13.680354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81620c1490e9'
down_revision = '1638a5afc5a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign_stream',
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('stream_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['stream_id'], ['stream.id'], ),
    sa.PrimaryKeyConstraint('campaign_id', 'stream_id')
    )
    op.create_table('device_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stream_id', sa.Integer(), nullable=False),
    sa.Column('device_type', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['stream_id'], ['stream.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_type_id'), 'device_type', ['id'], unique=False)
    op.create_table('os_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stream_id', sa.Integer(), nullable=False),
    sa.Column('os_type', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['stream_id'], ['stream.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_os_type_id'), 'os_type', ['id'], unique=False)
    op.create_table('stream_device_type',
    sa.Column('device_type_id', sa.Integer(), nullable=False),
    sa.Column('stream_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['device_type_id'], ['device_type.id'], ),
    sa.ForeignKeyConstraint(['stream_id'], ['stream.id'], ),
    sa.PrimaryKeyConstraint('device_type_id', 'stream_id')
    )
    op.create_table('stream_geo_location',
    sa.Column('geo_location_id', sa.Integer(), nullable=False),
    sa.Column('stream_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['geo_location_id'], ['geo_location.id'], ),
    sa.ForeignKeyConstraint(['stream_id'], ['stream.id'], ),
    sa.PrimaryKeyConstraint('geo_location_id', 'stream_id')
    )
    op.create_table('stream_page',
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('stream_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['page.id'], ),
    sa.ForeignKeyConstraint(['stream_id'], ['stream.id'], ),
    sa.PrimaryKeyConstraint('page_id', 'stream_id')
    )
    op.create_table('stream_time_frame',
    sa.Column('time_frame_id', sa.Integer(), nullable=False),
    sa.Column('stream_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['stream_id'], ['stream.id'], ),
    sa.ForeignKeyConstraint(['time_frame_id'], ['time_frame.id'], ),
    sa.PrimaryKeyConstraint('time_frame_id', 'stream_id')
    )
    op.drop_index('ix_subcampaign_device_type_id', table_name='subcampaign_device_type')
    op.drop_table('subcampaign_device_type')
    op.add_column('stream_os_type', sa.Column('os_type_id', sa.Integer(), nullable=False))
    op.drop_index('ix_stream_os_type_id', table_name='stream_os_type')
    op.drop_constraint('stream_os_type_stream_id_fkey', 'stream_os_type', type_='foreignkey')
    op.create_foreign_key(None, 'stream_os_type', 'stream', ['stream_id'], ['id'])
    op.create_foreign_key(None, 'stream_os_type', 'os_type', ['os_type_id'], ['id'])
    op.drop_column('stream_os_type', 'os_type')
    op.drop_column('stream_os_type', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stream_os_type', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('stream_os_type', sa.Column('os_type', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'stream_os_type', type_='foreignkey')
    op.drop_constraint(None, 'stream_os_type', type_='foreignkey')
    op.create_foreign_key('stream_os_type_stream_id_fkey', 'stream_os_type', 'stream', ['stream_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_stream_os_type_id', 'stream_os_type', ['id'], unique=False)
    op.drop_column('stream_os_type', 'os_type_id')
    op.create_table('subcampaign_device_type',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('stream_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('device_type', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['stream_id'], ['stream.id'], name='subcampaign_device_type_stream_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='subcampaign_device_type_pkey')
    )
    op.create_index('ix_subcampaign_device_type_id', 'subcampaign_device_type', ['id'], unique=False)
    op.drop_table('stream_time_frame')
    op.drop_table('stream_page')
    op.drop_table('stream_geo_location')
    op.drop_table('stream_device_type')
    op.drop_index(op.f('ix_os_type_id'), table_name='os_type')
    op.drop_table('os_type')
    op.drop_index(op.f('ix_device_type_id'), table_name='device_type')
    op.drop_table('device_type')
    op.drop_table('campaign_stream')
    # ### end Alembic commands ###