"""

Revision ID: 8239f8c8d622
Revises: 0576019ba807
Create Date: 2025-01-14 16:02:39.583282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8239f8c8d622'
down_revision = '0576019ba807'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###