"""

Revision ID: 858d644a14b0
Revises: 9933bb14f690
Create Date: 2025-01-14 16:24:22.938292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '858d644a14b0'
down_revision = '9933bb14f690'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###