"""

Revision ID: 88b39d7250c0
Revises: 89d5dee52a90
Create Date: 2025-01-04 11:13:08.566049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88b39d7250c0'
down_revision = '89d5dee52a90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###