"""

Revision ID: 892d006bc783
Revises: 90a681c85638
Create Date: 2025-01-29 18:18:14.952453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '892d006bc783'
down_revision = '90a681c85638'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###