"""

Revision ID: 89d5dee52a90
Revises: dafcf814c11c
Create Date: 2025-01-04 11:11:39.861343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89d5dee52a90'
down_revision = 'dafcf814c11c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###