"""

Revision ID: 90a681c85638
Revises: dedd332b61b2
Create Date: 2025-01-29 17:31:35.601365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90a681c85638'
down_revision = 'dedd332b61b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fragment', 'directory_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('project', sa.Column('directory_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'project', 'filesystem_directory', ['directory_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project', type_='foreignkey')
    op.drop_column('project', 'directory_id')
    op.alter_column('fragment', 'directory_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###