"""

Revision ID: 958a8b416981
Revises: 858d644a14b0
Create Date: 2025-01-14 16:31:03.431472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '958a8b416981'
down_revision = '858d644a14b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fragment_usage',
    sa.Column('fragment_id', sa.Integer(), nullable=False),
    sa.Column('used_fragment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fragment_id'], ['fragment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['used_fragment_id'], ['fragment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('fragment_id', 'used_fragment_id')
    )
    op.drop_table('linked_fragment')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('linked_fragment',
    sa.Column('linked_fragment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fragment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['fragment_id'], ['fragment.id'], name='linked_fragment_fragment_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['linked_fragment_id'], ['fragment.id'], name='linked_fragment_linked_fragment_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('linked_fragment_id', 'fragment_id', name='linked_fragment_pkey')
    )
    op.drop_table('fragment_usage')
    # ### end Alembic commands ###