"""

Revision ID: 9933bb14f690
Revises: 3b49dbb0f78c
Create Date: 2025-01-14 16:11:54.024626

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9933bb14f690'
down_revision = '3b49dbb0f78c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_linked_fragment_id', table_name='linked_fragment')
    op.drop_column('linked_fragment', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('linked_fragment', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_index('ix_linked_fragment_id', 'linked_fragment', ['id'], unique=False)
    # ### end Alembic commands ###