"""

Revision ID: 9bf9c60968f6
Revises: be915753f84c
Create Date: 2025-01-06 12:12:36.866165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bf9c60968f6'
down_revision = 'be915753f84c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###