"""

Revision ID: 9ed26d75b8cd
Revises: a24ae796095b
Create Date: 2025-01-06 12:33:37.783124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ed26d75b8cd'
down_revision = 'a24ae796095b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###