"""

Revision ID: a24ae796095b
Revises: 9bf9c60968f6
Create Date: 2025-01-06 12:32:48.779120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a24ae796095b'
down_revision = '9bf9c60968f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###