"""

Revision ID: a33b86e616fa
Revises: 20f8938dbf90
Create Date: 2025-01-14 15:43:30.305748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a33b86e616fa'
down_revision = '20f8938dbf90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###