"""

Revision ID: b7a71c280d67
Revises: fd85818e3038
Create Date: 2025-01-14 15:38:19.930246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7a71c280d67'
down_revision = 'fd85818e3038'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###