"""

Revision ID: be915753f84c
Revises: 07fcae5c0d37
Create Date: 2025-01-04 16:53:20.511557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be915753f84c'
down_revision = '07fcae5c0d37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fragment', sa.Column('project_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'fragment', 'project', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fragment', type_='foreignkey')
    op.drop_column('fragment', 'project_id')
    # ### end Alembic commands ###