"""

Revision ID: c5936808f98a
Revises: eb1c25b9b572
Create Date: 2024-10-22 20:39:17.372472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5936808f98a'
down_revision = 'eb1c25b9b572'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fragment_media_fragment_id_fkey', 'fragment_media', type_='foreignkey')
    op.drop_constraint('fragment_media_media_id_fkey', 'fragment_media', type_='foreignkey')
    op.create_foreign_key(None, 'fragment_media', 'fragment', ['fragment_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'fragment_media', 'media', ['media_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fragment_media', type_='foreignkey')
    op.drop_constraint(None, 'fragment_media', type_='foreignkey')
    op.create_foreign_key('fragment_media_media_id_fkey', 'fragment_media', 'fragment', ['media_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fragment_media_fragment_id_fkey', 'fragment_media', 'media', ['fragment_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###