"""

Revision ID: d725a52d97f2
Revises: 1d9921caf11e
Create Date: 2025-01-14 14:55:33.856849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd725a52d97f2'
down_revision = '1d9921caf11e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###