"""

Revision ID: d7b32fd21107
Revises: 228aa626ea93
Create Date: 2025-01-06 19:23:24.346384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7b32fd21107'
down_revision = '228aa626ea93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('linked_fragment',
    sa.Column('linked_fragment_id', sa.Integer(), nullable=False),
    sa.Column('fragment_version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['fragment_version_id'], ['fragment_version.id'], ),
    sa.ForeignKeyConstraint(['linked_fragment_id'], ['fragment.id'], ),
    sa.PrimaryKeyConstraint('linked_fragment_id', 'fragment_version_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('linked_fragment')
    # ### end Alembic commands ###