"""

Revision ID: da522a6abe63
Revises: 7800657f96c6
Create Date: 2024-11-07 16:37:04.472793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da522a6abe63'
down_revision = '7800657f96c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('landing', 'fragment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('stream', sa.Column('project_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'stream', 'project', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stream', type_='foreignkey')
    op.drop_column('stream', 'project_id')
    op.alter_column('landing', 'fragment_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###