"""

Revision ID: dafcf814c11c
Revises: cb1c2abd4a82
Create Date: 2025-01-04 11:10:20.305464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dafcf814c11c'
down_revision = 'cb1c2abd4a82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fragment_version', sa.Column('fragment_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'fragment_version', 'fragment', ['fragment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'fragment_version', type_='foreignkey')
    op.drop_column('fragment_version', 'fragment_id')
    # ### end Alembic commands ###