"""

Revision ID: e678ff648bed
Revises: 5db01980ac90
Create Date: 2025-03-02 14:34:54.393124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e678ff648bed'
down_revision = '5db01980ac90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('project_private_key_id_key', 'project', type_='unique')
    op.drop_constraint('project_private_key_id_fkey', 'project', type_='foreignkey')
    op.create_foreign_key(None, 'project', 'project_api_key', ['private_key_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project', type_='foreignkey')
    op.create_foreign_key('project_private_key_id_fkey', 'project', 'project_api_key', ['private_key_id'], ['id'], ondelete='SET NULL')
    op.create_unique_constraint('project_private_key_id_key', 'project', ['private_key_id'])
    # ### end Alembic commands ###