"""

Revision ID: fb816be4ef5f
Revises: 892d006bc783
Create Date: 2025-01-29 18:34:56.432376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb816be4ef5f'
down_revision = '892d006bc783'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###