"""

Revision ID: ff4942da4db5
Revises: 5a9f7fc05b8f
Create Date: 2024-11-26 19:54:13.694817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff4942da4db5'
down_revision = '5a9f7fc05b8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('geo_location_stream_id_fkey', 'geo_location', type_='foreignkey')
    op.drop_column('geo_location', 'stream_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('geo_location', sa.Column('stream_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('geo_location_stream_id_fkey', 'geo_location', 'stream', ['stream_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###