query StreamLocationFilter {
    filter(countries: [], regions: []) {
        geoLocations {
            country
#            regions {
#                region
#                cities
#            }
        }
    }
}
