query CurrentUser {
    profile {
        user {
            id
            email
            firstName
            lastName
            logo {
                publicPath
            }
        }
        accessToken
        refreshToken
    }
}
