query Campaign($areaId: Int, $id: Int) {
    campaign(areaId: $areaId, campaignId: $id) {
        id
        name
        active
        logo {
            url: publicPath
        }
        default
        featureFlag {
            id
            name
            releaseCondition {
                id
                conditionSets {
                    conditions {
                        filterType
                    }
                }
            }
            variants {
                rolloutPercentage
                rotationType
                fragment {
                    fragment {
                        id
                    }
                    props
                }
            }
        }
    }
}
