mutation CreateCampaign($areaId: Int!, $name: String!, $status: CampaignStatus!) {
    createCampaign(cmp: {areaId: $areaId,name: $name, status: $status }) {
        id
        name
        status
    }
}
