# import ../../../../../shared/api/fragments/ReleaseCondition.gql

query ListCampaigns($areaId: Int!) {
    campaign(campaignFilter: {areaId: $areaId}) {
        id
        name
        status
#        default
        logo {
            publicPath
        }
        featureFlag {
            releaseCondition {
                ...ReleaseCondition
            }
        }
    }
}
