query ListCampaigns($areaId: Int!) {
    campaign(areaId: $areaId) {
        id
        name
        status
#        default
        logo {
            publicPath
        }
        featureFlag {
            releaseCondition {
                id
                conditionSets {
                    id
                    name
                    conditions {
                        id
                    }
                }
            }
        }
    }
}
