'use client'
import React, { FC, ReactNode, useEffect, useMemo } from 'react'
import { createCanvasManager } from '../lib/canvasManager'
import { createPreviewManager } from '../lib/previewManager'
import { createBuilderManager } from '../lib/builderManager'
import { createState } from '@graph-state/core'
import { BuilderContext } from '@/shared/providers/BuilderContext'
import loggerPlugin from '@graph-state/plugin-logger'
// import { BuilderPreview } from '@/builder/views/BuilderPreview/BuilderPreview'
// import { useHotkeysContext } from 'react-hotkeys-hook'
// import { hotKeysScope } from '@/app/hooks/hotkeys/HotKeysProvider'
import fragmentData from '../fragment.json'
import fragmentButtonData from '../button.fragment.json'
import pluginState, { skips as stateSkips } from '@fragments/plugin-fragment-spring'
import { generateId, isBrowser } from '@fragments/utils'
import { useParams } from 'next/navigation'
import pluginFragment from '@fragments/plugin-fragment'
import pluginFragmentSpring, { skips } from '@fragments/plugin-fragment-spring'

const canvasManager = createCanvasManager()
const previewManager = createPreviewManager()
const builderManager = createBuilderManager()

const nextFragmentState = createState({
  initialState: {},
  plugins: [pluginFragmentSpring('Fragment:g34gherhg3g'), loggerPlugin({ onlyBrowser: true })],
  skip: [...stateSkips, ...skips]
})

export const stateAlias = '$fragment'

nextFragmentState.fragment = 'Fragment:g34gherhg3g'

nextFragmentState.$fragment.applySnapshot({
  'Fragment:g34gherhg3g': {
    _type: 'Fragment',
    _id: 'g34gherhg3g',
    children: ['Frame:d12bd11e59ee4'],
    layoutSizingHorizontal: 'Fixed',
    layoutSizingVertical: 'Fixed',
    horizontalGrow: 'auto',
    verticalGrow: 'auto',
    renderTarget: 'canvas',
    renderMode: 'parent',
    name: 'BannerWidget',
    opacity: 1,
    visible: true,
    overflow: 'hidden',
    overrides: [],
    properties: ['Variable:8e348e2255afd']
  },
  'Frame:d12bd11e59ee4': {
    _type: 'Frame',
    _id: 'd12bd11e59ee4',
    opacity: 1,
    visible: true,
    overflow: 'visible',
    children: ['Frame:9c86393a0a501', 'Frame:bf32614cc22ae', 'Frame:9896dbb5f5ffd'],
    width: 240,
    height: 96.71772112485017,
    layoutSizingHorizontal: 'Fixed',
    layoutSizingVertical: 'Hug',
    rotation: 0,
    cornerRadius: 4,
    topLeftRadius: 0,
    topRightRadius: 0,
    bottomLeftRadius: 0,
    bottomRightRadius: 0,
    layerMode: 'flex',
    layerAlign: 'start',
    layerDirection: 'vertical',
    layerDistribute: 'space-between',
    layerGap: 10,
    borderType: 'None',
    borderWidth: 1,
    fillType: 'Solid',
    left: 0,
    top: 0,
    positionType: 'absolute',
    parent: '$$Fragment:g34gherhg3g',
    padding: 10,
    paddingLeft: 30,
    paddingRight: 30,
    paddingTop: 30,
    paddingBottom: 30,
    layerWrap: false,
    solidFill: 'rgba(255, 255, 255, 1)',
    overrides: ['$$Frame:214dba74ab1c5'],
    name: 'card'
  },
  'Frame:9c86393a0a501': {
    _type: 'Frame',
    _id: '9c86393a0a501',
    name: 'Head',
    overrides: ['$$Frame:8a106526d4b4c'],
    children: ['Frame:c1b8a87401ba1', 'Frame:58d53471ec9c7', 'Text:152808e346fee'],
    parent: '$$Frame:d12bd11e59ee4',
    top: 0,
    left: 0,
    positionType: 'relative',
    width: 200,
    height: 200,
    layoutSizingHorizontal: 'Fill',
    layoutSizingVertical: 'Hug',
    visible: true,
    opacity: 1,
    overflow: 'hidden',
    solidFill: 'rgba(86, 177, 196, 1)',
    cornerRadius: 0,
    topLeftRadius: 0,
    topRightRadius: 0,
    bottomLeftRadius: 0,
    bottomRightRadius: 0,
    layerMode: 'flex',
    layerAlign: 'center',
    layerDirection: 'horizontal',
    layerDistribute: 'start',
    layerWrap: false,
    layerGap: 10,
    padding: 0,
    paddingLeft: 0,
    paddingRight: 0,
    paddingTop: 0,
    paddingBottom: 0
  },
  'Frame:c1b8a87401ba1': {
    _type: 'Frame',
    _id: 'c1b8a87401ba1',
    overrides: ['$$Frame:e28b2fe2fb39e'],
    children: ['Text:28a61138e386e', 'Text:d7167bbcc0b46'],
    parent: '$$Frame:9c86393a0a501',
    top: 0,
    left: 0,
    positionType: 'relative',
    width: 200,
    height: 200,
    layoutSizingHorizontal: 'Hug',
    layoutSizingVertical: 'Hug',
    visible: true,
    opacity: 1,
    overflow: 'hidden',
    solidFill: 'rgba(72, 44, 196, 1)',
    cornerRadius: 0,
    topLeftRadius: 0,
    topRightRadius: 0,
    bottomLeftRadius: 0,
    bottomRightRadius: 0,
    layerMode: 'flex',
    layerAlign: 'start',
    layerDirection: 'horizontal',
    layerDistribute: 'start',
    layerWrap: false,
    layerGap: 7,
    padding: 0,
    paddingLeft: 0,
    paddingRight: 0,
    paddingTop: 0,
    paddingBottom: 0
  },
  'Text:28a61138e386e': {
    _type: 'Text',
    _id: '28a61138e386e',
    name: 'Date',
    overrides: ['$$Text:245b85b31532'],
    children: [],
    parent: '$$Frame:c1b8a87401ba1',
    top: 36.63781212137166,
    left: 46.83902176777932,
    positionType: 'relative',
    width: 200,
    height: 200,
    layoutSizingHorizontal: 'Hug',
    layoutSizingVertical: 'Hug',
    visible: true,
    opacity: 1,
    overflow: 'hidden',
    content: '<p><span style="color: rgb(60, 59, 67)">18:00</span></p>',
    whiteSpace: 'nowrap'
  },
  'Text:28a61138e386e.styleAttributes': {
    _type: 'Text',
    _id: '28a61138e386e.styleAttributes'
  },
  'Text:d7167bbcc0b46': {
    _type: 'Text',
    _id: 'd7167bbcc0b46',
    name: 'Time',
    overrides: ['$$Text:37ad3f527a4fd'],
    children: [],
    parent: '$$Frame:c1b8a87401ba1',
    top: 36.63781212137166,
    left: 99.39850977205957,
    positionType: 'relative',
    width: 200,
    height: 200,
    layoutSizingHorizontal: 'Hug',
    layoutSizingVertical: 'Hug',
    visible: true,
    opacity: 1,
    overflow: 'hidden',
    content: '<p><span style="color: rgb(60, 59, 67)">18:00</span></p>',
    whiteSpace: 'nowrap'
  },
  'Text:d7167bbcc0b46.styleAttributes': {
    _type: 'Text',
    _id: 'd7167bbcc0b46.styleAttributes'
  },
  'Frame:58d53471ec9c7': {
    _type: 'Frame',
    _id: '58d53471ec9c7',
    overrides: ['$$Frame:c9d0e239ed304'],
    children: [],
    parent: '$$Frame:9c86393a0a501',
    top: 0,
    left: 0,
    positionType: 'relative',
    width: 5,
    height: 5,
    layoutSizingHorizontal: 'Fixed',
    layoutSizingVertical: 'Fixed',
    visible: true,
    opacity: 1,
    overflow: 'hidden',
    solidFill: 'rgba(216, 216, 216, 1)',
    fillType: 'Solid',
    cornerRadius: 10,
    topLeftRadius: 0,
    topRightRadius: 0,
    bottomLeftRadius: 0,
    bottomRightRadius: 0,
    layerMode: 'none',
    layerAlign: 'start',
    layerDirection: 'horizontal',
    layerDistribute: 'start',
    layerWrap: false,
    layerGap: 0,
    padding: 0,
    paddingLeft: 0,
    paddingRight: 0,
    paddingTop: 0,
    paddingBottom: 0
  },
  'Text:152808e346fee': {
    _type: 'Text',
    _id: '152808e346fee',
    name: 'league',
    overrides: ['$$Text:d0aad1f7e2136'],
    children: [],
    parent: '$$Frame:9c86393a0a501',
    top: 85.69881529039397,
    left: 95.74857537683376,
    positionType: 'relative',
    width: 200,
    height: 200,
    layoutSizingHorizontal: 'Hug',
    layoutSizingVertical: 'Hug',
    visible: true,
    opacity: 1,
    overflow: 'hidden',
    content:
      '<p style="font-size: 22px"><span style="color: rgb(66, 47, 163)">T</span><span style="font-size: 16px; color: rgb(66, 47, 163)">eam</span><span style="color: rgb(66, 47, 163)"> A</span></p>',
    whiteSpace: 'nowrap'
  },
  'Text:152808e346fee.styleAttributes': {
    _type: 'Text',
    _id: '152808e346fee.styleAttributes',
    fontSize: '22px',
    fontWeight: '',
    textAlign: 'left',
    textTransform: '',
    textDecoration: '',
    lineHeight: '',
    letterSpacing: ''
  },
  'Frame:bf32614cc22ae': {
    _type: 'Frame',
    _id: 'bf32614cc22ae',
    name: 'Teams',
    overrides: ['$$Frame:19a71c0cac27c'],
    children: ['Frame:692c0173e321a', 'Frame:f1cf861e61e21'],
    parent: '$$Frame:d12bd11e59ee4',
    top: 0,
    left: 0,
    positionType: 'relative',
    width: 200,
    height: 200,
    layoutSizingHorizontal: 'Fill',
    layoutSizingVertical: 'Hug',
    visible: true,
    opacity: 1,
    overflow: 'hidden',
    solidFill: 'rgba(72, 44, 196, 1)',
    cornerRadius: 0,
    topLeftRadius: 0,
    topRightRadius: 0,
    bottomLeftRadius: 0,
    bottomRightRadius: 0,
    layerMode: 'flex',
    layerAlign: 'center',
    layerDirection: 'horizontal',
    layerDistribute: 'start',
    layerWrap: false,
    layerGap: 11,
    padding: 0,
    paddingLeft: 0,
    paddingRight: 0,
    paddingTop: 0,
    paddingBottom: 0
  },
  'Frame:692c0173e321a': {
    _type: 'Frame',
    _id: '692c0173e321a',
    name: 'Logos',
    overrides: ['$$Frame:c4d37e0fd110d'],
    children: ['Frame:63f57b7c15051', 'Frame:b9e5d9c317bf8'],
    parent: '$$Frame:bf32614cc22ae',
    top: 0,
    left: 0,
    positionType: 'relative',
    width: 200,
    height: 200,
    layoutSizingHorizontal: 'Hug',
    layoutSizingVertical: 'Hug',
    visible: true,
    opacity: 1,
    overflow: 'hidden',
    solidFill: 'rgba(72, 44, 196, 1)',
    cornerRadius: 0,
    topLeftRadius: 0,
    topRightRadius: 0,
    bottomLeftRadius: 0,
    bottomRightRadius: 0,
    layerMode: 'flex',
    layerAlign: 'start',
    layerDirection: 'horizontal',
    layerDistribute: 'start',
    layerWrap: false,
    layerGap: 5,
    padding: 0,
    paddingLeft: 0,
    paddingRight: 0,
    paddingTop: 0,
    paddingBottom: 0
  },
  'Frame:63f57b7c15051': {
    _type: 'Frame',
    _id: '63f57b7c15051',
    name: 'Logo a',
    overrides: ['$$Frame:e924ad673c699'],
    children: [],
    parent: '$$Frame:692c0173e321a',
    top: 0,
    left: 0,
    positionType: 'relative',
    width: 25,
    height: 25,
    layoutSizingHorizontal: 'Fixed',
    layoutSizingVertical: 'Fixed',
    visible: true,
    opacity: 1,
    overflow: 'hidden',
    solidFill: 'rgba(195, 195, 195, 1)',
    fillType: 'Solid',
    cornerRadius: 4,
    topLeftRadius: 0,
    topRightRadius: 0,
    bottomLeftRadius: 0,
    bottomRightRadius: 0,
    layerMode: 'none',
    layerAlign: 'start',
    layerDirection: 'horizontal',
    layerDistribute: 'start',
    layerWrap: false,
    layerGap: 0,
    padding: 0,
    paddingLeft: 0,
    paddingRight: 0,
    paddingTop: 0,
    paddingBottom: 0
  },
  'Frame:b9e5d9c317bf8': {
    _type: 'Frame',
    _id: 'b9e5d9c317bf8',
    name: 'Logo B',
    overrides: ['$$Frame:2a1f3a925786e'],
    children: [],
    parent: '$$Frame:692c0173e321a',
    top: 0,
    left: 0,
    positionType: 'relative',
    width: 25,
    height: 25,
    layoutSizingHorizontal: 'Fixed',
    layoutSizingVertical: 'Fixed',
    visible: true,
    opacity: 1,
    overflow: 'hidden',
    solidFill: 'rgba(195, 195, 195, 1)',
    fillType: 'Solid',
    cornerRadius: 4,
    topLeftRadius: 0,
    topRightRadius: 0,
    bottomLeftRadius: 0,
    bottomRightRadius: 0,
    layerMode: 'none',
    layerAlign: 'start',
    layerDirection: 'horizontal',
    layerDistribute: 'start',
    layerWrap: false,
    layerGap: 0,
    padding: 0,
    paddingLeft: 0,
    paddingRight: 0,
    paddingTop: 0,
    paddingBottom: 0
  },
  'Frame:f1cf861e61e21': {
    _type: 'Frame',
    _id: 'f1cf861e61e21',
    name: 'Names',
    overrides: ['$$Frame:d5d0c85d8cb04'],
    children: ['Text:146eb8ee59b67', 'Text:600e451e283ba'],
    parent: '$$Frame:bf32614cc22ae',
    top: 0,
    left: 0,
    positionType: 'relative',
    width: 200,
    height: 200,
    layoutSizingHorizontal: 'Hug',
    layoutSizingVertical: 'Hug',
    visible: true,
    opacity: 1,
    overflow: 'hidden',
    solidFill: 'rgba(86, 177, 196, 1)',
    cornerRadius: 0,
    topLeftRadius: 0,
    topRightRadius: 0,
    bottomLeftRadius: 0,
    bottomRightRadius: 0,
    layerMode: 'flex',
    layerAlign: 'start',
    layerDirection: 'vertical',
    layerDistribute: 'start',
    layerWrap: false,
    layerGap: 0,
    padding: 0,
    paddingLeft: 0,
    paddingRight: 0,
    paddingTop: 0,
    paddingBottom: 0
  },
  'Text:146eb8ee59b67': {
    _type: 'Text',
    _id: '146eb8ee59b67',
    name: 'Team a name',
    overrides: ['$$Text:313725bff62ce'],
    children: [],
    parent: '$$Frame:f1cf861e61e21',
    top: 0,
    left: 0,
    positionType: 'relative',
    width: 200,
    height: 200,
    layoutSizingHorizontal: 'Hug',
    layoutSizingVertical: 'Hug',
    visible: true,
    opacity: 1,
    overflow: 'hidden',
    content: '<p><span style="color: rgb(66, 47, 163)">Team A</span></p>',
    whiteSpace: 'nowrap'
  },
  'Text:146eb8ee59b67.styleAttributes': {
    _type: 'Text',
    _id: '146eb8ee59b67.styleAttributes'
  },
  'Text:600e451e283ba': {
    _type: 'Text',
    _id: '600e451e283ba',
    name: 'Team B name',
    overrides: ['$$Text:ca21c87f8bd26'],
    children: [],
    parent: '$$Frame:f1cf861e61e21',
    top: 0,
    left: 0,
    positionType: 'relative',
    width: 200,
    height: 200,
    layoutSizingHorizontal: 'Hug',
    layoutSizingVertical: 'Hug',
    visible: true,
    opacity: 1,
    overflow: 'hidden',
    content: '<p><span style="color: rgb(66, 47, 163)">Team A</span></p>',
    whiteSpace: 'nowrap'
  },
  'Text:600e451e283ba.styleAttributes': {
    _type: 'Text',
    _id: '600e451e283ba.styleAttributes'
  },
  'Frame:9896dbb5f5ffd': {
    _type: 'Frame',
    _id: '9896dbb5f5ffd',
    name: 'Footer',
    overrides: ['$$Frame:b5b22f1a8f004'],
    children: ['Text:25cc5d58526da', 'Frame:75f5d5d76c5a5'],
    parent: '$$Frame:d12bd11e59ee4',
    top: 0,
    left: 0,
    positionType: 'relative',
    width: 222.66767199690628,
    height: 28,
    layoutSizingHorizontal: 'Fixed',
    layoutSizingVertical: 'Fixed',
    visible: true,
    opacity: 1,
    overflow: 'hidden',
    solidFill: 'rgba(228, 228, 228, 1)',
    fillType: 'Solid',
    cornerRadius: 4,
    topLeftRadius: 0,
    topRightRadius: 0,
    bottomLeftRadius: 0,
    bottomRightRadius: 0,
    layerMode: 'flex',
    layerAlign: 'center',
    layerDirection: 'horizontal',
    layerDistribute: 'space-between',
    layerWrap: false,
    layerGap: 10,
    padding: 0,
    paddingLeft: 10,
    paddingRight: 5,
    paddingTop: 2,
    paddingBottom: 2
  },
  'Text:25cc5d58526da': {
    _type: 'Text',
    _id: '25cc5d58526da',
    name: 'Text',
    overrides: ['$$Text:4b4d410e75e6c'],
    children: [],
    parent: '$$Frame:9896dbb5f5ffd',
    top: 0,
    left: 0,
    positionType: 'relative',
    width: 200,
    height: 200,
    layoutSizingHorizontal: 'Hug',
    layoutSizingVertical: 'Hug',
    visible: true,
    opacity: 1,
    overflow: 'hidden',
    content: 'Прогноз',
    whiteSpace: 'normal'
  },
  'Text:25cc5d58526da.styleAttributes': {
    _type: 'Text',
    _id: '25cc5d58526da.styleAttributes'
  },
  'Frame:75f5d5d76c5a5': {
    _type: 'Frame',
    _id: '75f5d5d76c5a5',
    name: 'Footer button',
    overrides: ['$$Frame:aeaa16e771399'],
    children: ['Text:047a7710ba1fc'],
    parent: '$$Frame:9896dbb5f5ffd',
    top: 0,
    left: 0,
    positionType: 'relative',
    width: 200,
    height: 200,
    layoutSizingHorizontal: 'Hug',
    layoutSizingVertical: 'Fill',
    visible: true,
    opacity: 1,
    overflow: 'hidden',
    solidFill: 'rgba(255, 255, 255, 1)',
    fillType: 'Solid',
    cornerRadius: 4,
    topLeftRadius: 0,
    topRightRadius: 0,
    bottomLeftRadius: 0,
    bottomRightRadius: 0,
    layerMode: 'flex',
    layerAlign: 'center',
    layerDirection: 'horizontal',
    layerDistribute: 'start',
    layerWrap: false,
    layerGap: 0,
    padding: 0,
    paddingLeft: 7,
    paddingRight: 7,
    paddingTop: 0,
    paddingBottom: 0
  },
  'Text:047a7710ba1fc': {
    _type: 'Text',
    _id: '047a7710ba1fc',
    name: 'Odd vlaue',
    overrides: ['$$Text:965fa5896ba3d'],
    children: [],
    parent: '$$Frame:75f5d5d76c5a5',
    top: 0,
    left: 0,
    positionType: 'relative',
    width: 200,
    height: 200,
    layoutSizingHorizontal: 'Hug',
    layoutSizingVertical: 'Hug',
    visible: true,
    opacity: 1,
    overflow: 'hidden',
    content: '2.41',
    whiteSpace: 'normal',
    variableLink: 'Variable:8e348e2255afd'
  },
  'Text:047a7710ba1fc.styleAttributes': {
    _type: 'Text',
    _id: '047a7710ba1fc.styleAttributes'
  },
  'Variable:8e348e2255afd': {
    _type: 'Variable',
    _id: '8e348e2255afd',
    defaultValue: '2.41',
    name: 'Content',
    required: false,
    type: 'String',
    isTextarea: false
  }
})

if (isBrowser) {
  window.nextFrag = nextFragmentState
}

interface FragmentDetailProps {
  builder?: ReactNode
  preview?: ReactNode
}

export const FragmentDetail: FC<FragmentDetailProps> = ({ builder, preview }) => {
  const { fragmentSlug } = useParams()
  const [, view] = fragmentSlug || []

  useEffect(() => {
    nextFragmentState
      .resolve(nextFragmentState[stateAlias].root)
      .setRenderTarget(view === 'edit' ? 'canvas' : 'document')
  }, [view])

  return (
    <BuilderContext.Provider
      value={{ documentManager: nextFragmentState, canvasManager, previewManager, builderManager }}
    >
      {view === 'edit' ? builder : preview}
    </BuilderContext.Provider>
  )
}
