mutation CreatePublicToken($projectId: Int!, $name: String!) {
    addProjectPublicKey(projectId: $projectId, publicKeyName: $name) {
        id
        publicKeys {
            id
            name
            value
        }
    }
}
