query ProjectTokens($projectId: Int) {
    project(projectId: $projectId) {
        id
        privateKey {
            id
            name
            value
        }
        publicKeys {
            id
            name
            value
        }
    }
}
