query Project($projectSlug: Int!) {
    project(projectId: $projectSlug) {
        id
        name
        rootDirectoryId
        allowedOrigins {
            id
            origin
        }
        logo {
            publicPath
        }
    }
}
