query LandingDetail($landingId: Int!) {
    landing(landingId: $landingId) {
        id
        name
        active
        fragment {
            id
            name
        }
        weight
        props
    }
}
