"use client";
import {
  createContext,
  ReactNode,
  useContext,
  useEffect,
  useMemo,
  useRef,
} from "react";
import { renderToStaticMarkup } from "react-dom/server";
import type { Metadata } from "next";
import "./global.css";
import { createFragmentsClient } from "@fragmentsx/client-core";
import { useSearchParams, useServerInsertedHTML } from "next/navigation";
import { collectStyles, GlobalManager } from "@fragmentsx/render-react";
import { isBrowser } from "@fragmentsx/utils";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const WWW = ({ children }) => {
  const globalManager = createFragmentsClient({
    apiToken:
      "2-c27ab3aa225aa808f17bd6533bad353a-c2741dc2d86797e13f00efe902d6211fe7d07d0f5a6ef3c65ab1424ea5d6b8b8",
    isSelf: false,
  });

  const params = useSearchParams();
  const fragmentId = params.get("node");
  const isServerInserted = useRef(false);

  useEffect(() => {
    window.globalManager = globalManager;
    window.getDocumentManager = () =>
      globalManager.resolve(globalManager.key).fragmentsManagers[+fragmentId];
  }, []);

  useServerInsertedHTML(() => {
    if (!isServerInserted.current) {
      isServerInserted.current = true;

      // const styles = collectStyles(globalManager);

      // collectStyles(globalManager, renderToStaticMarkup);
      // const tags = await globalManager.extractStyleTags();

      // console.log(
      //   globalManager.resolve(globalManager.key).fragmentsManagers["16"]
      // );

      const styles = collectStyles(globalManager);

      return (
        <>
          {styles}
          {/*{styles.map((st) => (*/}
          {/*  <style dangerouslySetInnerHTML={{ __html: st }} />*/}
          {/*))}*/}
          {}
        </>
      );
    }
  });

  // useMemo(() => {
  //   collectStyles(globalManager);
  // }, []);

  return <GlobalManager value={globalManager}>{children}</GlobalManager>;
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <WWW>{children}</WWW>
      </body>
    </html>
  );
}
