import type { Metadata } from 'next'
import { Graduate } from 'next/font/google'
import '@/shared/styles/globals.css'
import { ApolloWrapper } from '@/app/providers/ApolloProvider/ApolloProvider'

const graduate = Graduate({
  weight: ['400'],
  display: 'swap',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en' className={graduate.className}>
      <body>
        <ApolloWrapper>{children}</ApolloWrapper>
      </body>
    </html>
  )
}
