import type { Metadata } from 'next'
import '@/shared/styles/globals.css'
import { ApolloWrapper } from '@/app/providers/ApolloProvider/ApolloProvider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body>
        <ApolloWrapper>{children}</ApolloWrapper>
      </body>
    </html>
  )
}
