mutation CreateStream($name: String!, $active: Boolean!, $weight: Float!, $campaignId: Int!) {
    createStream(stream: {name: $name, active: $active, weight: $weight, deleted: false, campaignId: $campaignId}) {
        id
        name
        weight
        active
    }
}
