mutation SendFeedback($type: IssueType!, $bug: BugPost, $feedback: FeedbackPost, $proposal: ProposalPost) {
    createIssue(issue: {type: $type, bug: $bug, feedback: $feedback, proposal: $proposal}) {
        type
        ticketLink
    }
}
