export * from 'src/defenitions'
export { getDefaultBorder } from 'src/props/border/border.performance'
export { getDefaultSolidFill } from 'src/props/fill/fill.performance'
export { managerPlugin } from 'src/modules/managerPlugin/managerPlugin.performance'
export { skips } from 'src/modules/skips/skips.performance'
