mutation AuthSignIn($email: String!, $password: String!) {
    login(email: $email, password: $password) {
        user {
            id
            email
            firstName
            lastName
        }
        accessToken
        refreshToken
    }
}
