query CampaignDetail($id: Int!) {
    campaign(campaignId: $id) {
        id
        name
        status
        featureFlag {
            id
            releaseCondition {
                id
                conditionSets {
                    id
                    conditions {
                        id
                        filterType
                        filterData {
                            ... on FilterDeviceTypeGet {
                                deviceType
                            }

                            ... on FilterOSTypeGet {
                                osType
                            }

                            ... on FilterGeoLocationGet  {
                                country
                                region
                                city
                            }

                            ... on FilterPageGet {
                                page
                            }

                            ... on FilterTimeFrameGet {
                                fromTime
                                toTime
                            }
                        }
                    }
                }
            }
        }
    }
}
