query FragmentDocument($fragmentSlug: Int!) {
    fragment(fragmentIds: [$fragmentSlug]) {
        id
        name
        document
        linkedFragments {
            id
            document
        }
    }
}
