mutation UpdateProject($projectSlug: Int!, $name: String, $properties: [JSON!]) {
    updateProject(pr: {id: $projectSlug, name: $name, properties: $properties}) {
        id
        name
        properties
    }
}
