name: Deploy and Restart Service

on:
  push:
    branches:
      - master  # Trigger the deployment on push to master main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code from repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up SSH (if needed for deployment)
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }} 

    # Step 3: Pull changes
    - name: Pull changes
      run: |
        ssh-keyscan -t rsa 85.192.29.65 >> ~/.ssh/known_hosts
        ssh githubuser@85.192.29.65 "cd /home/githubuser/fragments && git pull origin master"
    
    # Step 4: Restart the service (using systemd, for example)
    - name: Start docker-compose
      run: |
        ssh githubuser@85.192.29.65 "cd /home/githubuser/fragments && docker-compose down"
        ssh githubuser@85.192.29.65 "cd /home/githubuser/fragments && COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose up --build -d"

    - name: Wait for services to be ready
      run: sleep 5
    
    - name: Upgrade Database
      run: |
        ssh githubuser@85.192.29.65 "cd /home/githubuser/fragments && docker exec backend-core make db_upgrade"