name: Deploy and Restart Service

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }} 

    - name: Pull changes
      run: |
        ssh-keyscan -t rsa 85.192.29.65 >> ~/.ssh/known_hosts
        ssh githubuser@85.192.29.65 "cd /home/githubuser/fragments && git pull origin master"
    
    - name: clean up before deployment
      run: |
        ssh githubuser@85.192.29.65 "cd /home/githubuser/fragments && docker system prune -f"

    - name: Start docker-compose
      run: |
        ssh githubuser@85.192.29.65 "cd /home/githubuser/fragments && docker-compose down"
        ssh githubuser@85.192.29.65 "cd /home/githubuser/fragments && COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose up --build -d"

    - name: Wait for services to be ready
      run: sleep 5
    
    - name: Upgrade Database
      run: |
        ssh githubuser@85.192.29.65 "cd /home/githubuser/fragments && docker exec backend-core make db_upgrade"

    - name: clean up after deployment
      run: |
        ssh githubuser@85.192.29.65 "cd /home/githubuser/fragments && docker system prune -f"